schinese = {}

schinese.LangName = "schinese"

schinese.lang_pldied = "{num} 名玩家死亡"
schinese.lang_descaped = "{num} 名 D 级人员逃脱"
schinese.lang_sescaped = "{num} 个 SCP 逃脱"
schinese.lang_rescaped = "{num} 名研究员逃脱"
schinese.lang_dcaptured = "混沌分裂者营救了 {num} 名 D 级人员"
schinese.lang_rescorted = "机动特遣队疏散了 {num} 名研究员"
schinese.lang_teleported = "SCP-106 将 {num} 名玩家拖入了口袋空间"
schinese.lang_snapped = "SCP-173 扭断了 {num} 个人的脖子"
schinese.lang_zombies = 'SCP-049 “治愈”了 {num} 次'
schinese.lang_secret_found = "发现彩蛋/秘密"
schinese.lang_secret_nfound = "未发现彩蛋/秘密"

schinese.unknown = "未知"


schinese.play = "开始游戏"
schinese.resume = "继续"
schinese.settings = "设置"
schinese.leave = "离开"
schinese.credits = "制作人员"

schinese.class_unknown = "未知"

schinese.NRegistry = {
	scpready = "你能在下一回合被选为SCP",
	scpwait = "你还要等待 %s 回合才能被选为SCP"
}

schinese.NFailed = "无法使用此钥匙卡进行访问:%s"

schinese.version_title = "Rainval Breach"
schinese.version = "Alpha 阶段"
schinese.bugs = "请反馈Bug！"

schinese.lang_end1 = "游戏结束"
schinese.lang_end2 = "时不我待"
schinese.lang_end3 = "无法继续游戏"

schinese.escapemessages = {
	{
		main = "你逃脱了",
		txt = "你在 {t} 分钟内逃离了设施，干得漂亮！",
		txt2 = "如果由机动特遣队护送撤离，将获得更多经验值。",
		clr = Color(237, 28, 63),
	},
	{
		main = "你逃脱了",
		txt = "你在 {t} 分钟内逃离了设施，干得漂亮！",
		txt2 = "如果由混沌分裂者护送撤离，将获得更多经验值。",
		clr = Color(237, 28, 63),
	},
	{
		main = "你已撤离",
		txt = "你在 {t} 分钟内成功撤离设施，干得漂亮！",
		txt2 = "",
		clr = Color(237, 28, 63),
	},
	{
		main = "你逃脱了",
		txt = "你在 {t} 分钟内逃离了设施，干得漂亮！",
		txt2 = "",
		clr = Color(237, 28, 63),
	}
}

schinese.role = {}


schinese.SCP = "SCP"
schinese.role.SCP106 = "SCP-106"
schinese.role.SCP049 = "SCP-049"
schinese.role.SCP0492 = "SCP-049-2"
schinese.role.SCP638 = "SCP-638"
schinese.role.SCP076 = "SCP-076-2"
schinese.role.SCP006FR = "SCP-006-FR"
schinese.role.SCP1027RU = "SCP-1027-RU"
schinese.role.SCP062DE = "SCP-062-DE"
schinese.role.SCP8602 = "SCP-860-2"
schinese.role.SCP062FR = "SCP-062-FR"
schinese.role.SCP096 = "SCP-096"
schinese.role.SCP966 = "SCP-966"
schinese.role.SCP542 = "SCP-542"
schinese.role.SCP1903 = "SCP-1903"
schinese.role.SCP973 = "SCP-973"
schinese.role.SCP457 = "SCP-457"
schinese.role.SCP173 = "SCP-173"
schinese.role.SCP2012 = "SCP-2012"
schinese.role.SCP082 = "SCP-082"
schinese.role.SCP999 = "SCP-999-2"
schinese.role.SCP939 = "SCP-939"
schinese.role.SCP811 = "SCP-811"
schinese.role.SCP682 = "SCP-682"
schinese.role.SCP912 = "SCP-912"
schinese.role.SCP777 = "SCP-777"
schinese.role.SCP4975 = "SCP-4975"

schinese.SCI = "科研部门"
schinese.role.SCI_Assistant = "科研助手"
schinese.role.SCI_Grunt = "科研人员"
schinese.role.SCI_Grand = "高级研究员"
schinese.role.SCI_Recruiter = "道德伦理检察官"
schinese.role.SCI_Tester = "病毒学专家"
schinese.role.SCI_Medic = "医生"
-- schinese.role.SCI_Cleaner = "保洁员"
schinese.role.SCI_Head = "科研主管"
schinese.role.SCI_SpyUSA = "特异事故处 间谍"

schinese.SECURITY = "安保部门"
schinese.role.SECURITY_Recruit = "安保部门 菜逼"
schinese.role.SECURITY_Sergeant = "安保部门 中士"
schinese.role.SECURITY_OFFICER = "安保部门 警员"
schinese.role.SECURITY_Shocktrooper = "安保部门 调查员"
schinese.role.SECURITY_Warden = "安保部门 突击队员"
-- schinese.role.SECURITY_IMVSOLDIER = "安保特战员" // not usable now
schinese.role.SECURITY_Chief = "安保部门 上尉"
schinese.role.SECURITY_Spy = "混沌分裂者 间谍"

schinese.GRU = "格鲁乌“P”部门"
schinese.role.GRU_Soldier = "GRU-P 士兵"
schinese.role.GRU_Specialist = "GRU-P 特战员"
schinese.role.GRU_Jugg = "GRU-P 无畏战士"
schinese.role.GRU_Commander = "GRU-P 指挥官"

schinese.MINIGAMES = "其他模式"
schinese.role.USA = "美军士兵"
schinese.role.Nazi = "第三帝国士兵"
schinese.role.CTFCI = "混沌突袭者"
schinese.role.CTFQRT = "QRT 防守者"
schinese.role.ArenaParticipant = "角斗场参与者"

schinese.UIU = "特异事故处 (UIU)"
schinese.role.UIU_Soldier = "特异事故处 士兵"
schinese.role.UIU_Commander = "特异事故处 指挥官"
schinese.role.UIU_Specialist = "特异事故处 战斗专家"
schinese.role.UIU_Clocker = "特异事故处 渗透者"
schinese.role.UIU_Informator = "特异事故处 情报员"

schinese.SKP = "异常特遣队 (SKP)"
schinese.role.SKP_Soldat = "SKP 突击队员"
schinese.role.SKP_Jager = "SKP 猎兵"
schinese.role.SKP_Machinegunner = "SKP 机枪手"
schinese.role.SKP_Offizier = "SKP 军官"

schinese.DZ = "蛇之手 (SH)"
schinese.role.DZ_Grunt = "蛇之手 士兵"
schinese.role.SCI_SpyDZ = "蛇之手 间谍"
schinese.role.DZ_Gas = "蛇之手 特种探员"
schinese.role.DZ_Psycho = "蛇之手 疯子"
schinese.role.DZ_Commander = "蛇之手 指挥官"

schinese.Goc = "全球超自然联盟 (GOC)"
schinese.role.Goc_Grunt = "全球超自然联盟 士兵"
schinese.role.Goc_Liq = "全球超自然联盟 清理者"
schinese.role.Goc_Commander = "全球超自然联盟 指挥官"
schinese.role.Goc_Jag = "全球超自然联盟 重装"
schinese.role.Goc_Special = "全球超自然联盟 战斗专家"

schinese.QRT = "快速反应部队 (QRT)"
schinese.role.QRT_Soldier = "快速反应部队 士兵"
schinese.role.QRT_Medic = "快速反应部队 医疗兵"
schinese.role.QRT_ShockTrooper = "快速反应部队 突击队员"
schinese.role.QRT_Commander = "快速反应部队 指挥官"
schinese.role.QRT_Machinegunner = "快速反应部队 机枪手"
schinese.role.QRT_Shield = "快速反应部队 盾牌手"
schinese.role.QRT_Marksmen = "快速反应部队 精确射手"

schinese.STS = "特别任务小队 (STS)"
schinese.role.STS_Soldier = "STS 士兵"
schinese.role.STS_Shock = "STS 突击队员"
schinese.role.STS_Special = "STS 特战员"
schinese.role.STS_Officer = "STS 军官"
schinese.role.STS_Left = "STS 中尉" 

schinese.OSN = "特别任务小队"
schinese.role.OSN_Soldier = "STS 士兵"
schinese.role.OSN_Specialist = "STS 特战员"
schinese.role.OSN_Commander = "STS 指挥官"

schinese.ClassD = "D级人员"
schinese.role.ClassD_Default = "D级人员"
schinese.role.ClassD_Pron = "D级人员 小偷"
schinese.role.ClassD_Hack = "D级人员 黑客"
schinese.role.ClassD_Bor = "D级人员 摔跤手"
schinese.role.ClassD_Fat = "D级人员 胖宝宝"
-- schinese.role.ClassD_Probitiy = "异能 D 级"
schinese.role.ClassD_Thief = "D级人员 神偷"
schinese.role.ClassD_Cannibal = "D级人员 食人魔"
schinese.role.ClassD_Sportsman = "D级人员 运动员"
schinese.role.ClassD_Killer = "D级人员 杀手"
-- schinese.role.ClassD_Hitman = "刺客 D 级"
schinese.role.ClassD_FartInhaler = "D级人员 哥布林"
schinese.role.ClassD_GOCSpy = "全球超自然联盟 间谍"
schinese.role.ClassD_Banned = "惩罚D级人员"

schinese.MTF = "驻SITE19机动特遣队"
schinese.role.MTF_Security = "内部安全代理"
schinese.role.MTF_Shock = "机动特遣队 突击队员"
schinese.role.MTF_Guard = "机动特遣队 士兵"
schinese.role.MTF_Medic = "机动特遣队 医疗兵"
schinese.role.MTF_Left = "机动特遣队 中尉"
schinese.role.MTF_Chem = "机动特遣队 化学专家"
schinese.role.MTF_Specialist = "机动特遣队 战斗专家"
schinese.role.MTF_Com = "安全主管"
schinese.role.MTF_HOF = "设施主管"
schinese.role.MTF_Engi = "机动特遣队 工程师"
schinese.role.MTF_Jag = "机动特遣队 重装"
schinese.role.Dispatcher = "调度员"

schinese.role.TG_Nerd = "战术小队 新兵"
schinese.role.TG_Capral = "战术小队 下士"
schinese.role.TG_Ser = "战术小队 中士"
schinese.role.TG_SerPlus = "战术小队 上士"
schinese.role.TG_Left = "战术小队 中尉"
schinese.role.TG_Com = "战术小队 队长"

schinese.Chaos = "混沌分裂者"
schinese.role.Chaos_Grunt = "混沌分裂者 士兵"
schinese.role.Chaos_Commander = "混沌分裂者 指挥官"
schinese.role.Chaos_Jugg = "混沌分裂者 重装"
schinese.role.Chaos_Demo = "混沌分裂者 恶魔"
schinese.role.Chaos_Sabo = "混沌分裂者 爆破手"
schinese.role.Chaos_Recruit = "混沌分裂者 新兵"
schinese.chaos_support_call = "你呼叫了混沌分裂者突击分队！等待支援到达……"

schinese.SCI_SPECIAL = "特殊科学家"
schinese.role.SCI_SPECIAL_DAMAGE = "Kelen"
schinese.role.SCI_SPECIAL_HEALER = "Matilda"
schinese.role.SCI_SPECIAL_SLOWER = "Speedwone"
schinese.role.SCI_SPECIAL_SPEED = "Lomao"
schinese.role.SCI_SPECIAL_MINE = "Feelon"
schinese.role.SCI_SPECIAL_BOOSTER = "Georg"
schinese.role.SCI_SPECIAL_SHIELD = "Shieldmeh"
schinese.role.SCI_SPECIAL_INVISIBLE = "Ruprecht"
schinese.role.SCI_SPECIAL_VISION = "Hedwig"
schinese.role.SCI_SPECIAL_10 = "Oswalld"

schinese.Cult = "深红王之子"
schinese.role.Cult_Commander = "深红王之子 祭祀"
schinese.role.Cult_Grunt = "深红王之子 信徒"
schinese.role.Cult_Psycho = "深红王之子 狂信徒"
schinese.role.Cult_Specialist = "深红王之子 助祭"

schinese.weaponry = {}

schinese.weaponry["breach_keycard_1"] = "一级钥匙卡"
schinese.weaponry["breach_keycard_2"] = "二级钥匙卡"
schinese.weaponry["breach_keycard_3"] = "三级钥匙卡"
schinese.weaponry["breach_keycard_4"] = "四级钥匙卡"
schinese.weaponry["breach_keycard_5"] = "五级钥匙卡"

schinese.weaponry["breach_keycard_6"] = "Omni钥匙卡"
schinese.weaponry["breach_keycard_7"] = "O5钥匙卡"
schinese.weaponry["breach_keycard_crack"] = "? 级钥匙卡"
schinese.weaponry["breach_keycard_support"] = "? 级钥匙卡"

schinese.weaponry["breach_keycard_sci_1"] = "一级科研钥匙卡"
schinese.weaponry["breach_keycard_sci_2"] = "二级科研钥匙卡"
schinese.weaponry["breach_keycard_sci_3"] = "三级科研钥匙卡"
schinese.weaponry["breach_keycard_sci_4"] = "四级科研钥匙卡"

schinese.weaponry["breach_keycard_security_1"] = "一级安保钥匙卡"
schinese.weaponry["breach_keycard_security_2"] = "二级安保钥匙卡"
schinese.weaponry["breach_keycard_security_3"] = "三级安保钥匙卡"
schinese.weaponry["breach_keycard_security_4"] = "四级安保钥匙卡"

schinese.weaponry["breach_keycard_guard_1"] = "一级警卫钥匙卡"
schinese.weaponry["breach_keycard_guard_2"] = "二级警卫钥匙卡"
schinese.weaponry["breach_keycard_guard_3"] = "三级警卫钥匙卡"
schinese.weaponry["breach_keycard_guard_4"] = "四级警卫钥匙卡"

schinese.weaponry["item_drink_dado_fire"] = "DADO 果汁「好喝到\"爆\"!」"
schinese.weaponry["item_drink_dado_radioactive"] = "DADO 果汁「辐射风味」"
schinese.weaponry["item_drink_dado_speed"] = "DADO 果汁「根本停不下来!」"

schinese.weaponry["item_drink_energy"] = "能量饮料"
schinese.weaponry["item_drink_soda"] = "苏打水"
schinese.weaponry["item_drink_water"] = "罐装水"
schinese.weaponry["item_drink_coffee"] = "咖啡"

schinese.weaponry["item_eyedrops_1"] = "眼药水"
schinese.weaponry["item_eyedrops_2"] = "改进型眼药水"
schinese.weaponry["item_eyedrops_3"] = "实验型眼药水"

schinese.weaponry["item_hamburger"] = "汉堡"

schinese.weaponry["item_keys"] = "车钥匙"
schinese.weaponry["item_knife"] = "折叠小刀"

schinese.weaponry["item_medkit_1"] = "医疗包"
schinese.weaponry["item_medkit_2"] = "办公医疗包"
schinese.weaponry["item_medkit_3"] = "特护医疗包"
schinese.weaponry["item_medkit_4"] = "高级医疗包"
schinese.weaponry["item_pills"] = "止痛药"

schinese.weaponry["_kasanov_headlamp"] = "头灯"
schinese.weaponry["breach_nightvision_green"] = "夜视仪"
schinese.weaponry["breach_nightvision_blue"] = "蓝色夜视仪"
schinese.weaponry["breach_nightvision_thermal"] = "热成像夜视仪"
schinese.weaponry["breach_nightvision_goc"] = "GOC特供夜视仪"
schinese.weaponry["breach_nightvision_white"] = "原型夜视仪"

schinese.weaponry["item_radio"] = "对讲机"
schinese.weaponry["item_chaos_radio"] = "CI对讲机"

schinese.weaponry["item_adrenaline"] = "肾上腺素"
schinese.weaponry["item_syringe"] = "机能强化注射器"

schinese.weaponry["item_deffib_medic"] = "除颤仪"

schinese.weaponry["item_screwdriver"] = "螺丝刀"
schinese.weaponry["item_tazer"] = "电击器"
schinese.weaponry["item_toolkit"] = "工具箱"

schinese.weaponry["copper_coin"] = "铜币"
schinese.weaponry["silver_coin"] = "银币"
schinese.weaponry["gold_coin"] = "金币"

schinese.weaponry["breach_weapon_gauss"] = "电磁炮"

schinese.weaponry["br_holster"] = "徒手"

schinese.weaponry["weapon_flashlight"] = "手电筒"

schinese.weaponry["weapon_pass_guard"] = "身份卡「军事人员」"
schinese.weaponry["weapon_pass_medic"] = "身份卡「医疗人员」"
schinese.weaponry["weapon_pass_sci"] = "身份卡「科研人员」"

schinese.weaponry["weapon_breachmelee_crowbar"] = "撬棍"
schinese.weaponry["weapon_breachmelee_wrench"] = "扳手"
schinese.weaponry["weapon_breachmelee_hammer"] = "铁锤"
schinese.weaponry["weapon_breachmelee_fireaxe"] = "消防斧"
schinese.weaponry["weapon_breachmelee_batton"] = "警棍"

schinese.weaponry["weapon_cannibal"] = "行动：食人"
schinese.weaponry["weapon_cqc"] = "行动：缴械"
schinese.weaponry["breach_keycard_usa_spy"] = "内部钥匙卡"
schinese.weaponry["weapon_usa_instruction"] = "教诲"
schinese.weaponry["ritual_paper"] = "卷轴"

schinese.role.Spectator = "旁观者"

--Let the great translation be well and mighty.


--BREACH TIPS
schinese.already_have_the_bag = "你已经有背包了!"
schinese.took_on_the_bag = "你穿上了背包!"
schinese.you_cant_wear_the_bag = "你不能穿背包!"
schinese.has_uniform_already = "你已经有衣服了."
schinese.take_off_armor_to_wear_uniform = "脱掉你的护甲才能穿上这件衣服!"
schinese.your_uniform_is = "你穿上了:"
schinese.has_helmet_already = "你已经有头盔了."
schinese.take_off_uniform_to_wear_helmet = "脱下你的衣服才能戴上这个头盔!"
schinese.put_on_helmet = "你戴上了头盔!"
schinese.you_cant_wear_helmet = "你不能戴头盔!"
schinese.take_off_vest_to_wear_vest = "你已经有防弹衣了."
schinese.take_off_uniform_to_wear_vest = "脱下你的衣服才能传上这个防弹衣!"
schinese.put_on_vest = "你穿上了防弹衣!"
schinese.you_cant_wear_vest = "你不能穿防弹衣!"
schinese.goc_nuke_start = "Alpha核弹已被非法激活 所有战斗人员 - 立刻阻止!"
schinese.repaired_generators_count = "已被维修的发电机数量:"
schinese.you_ate_burger = "你吃了个蟹黄堡,恢复了生命值."
schinese.you_ate_burger_hp_regenerated_pt1 = "你吃饱了 "
schinese.you_ate_burger_hp_regenerated_pt2 = " 你变健康了."
schinese.dont_go_far_away_from_body = "你不能离尸体太远了"
schinese.scp427_regenerates_health = "SCP-427 缓慢地恢复了你的生命值."
schinese.you_took_off_scp427 = "你卸下了 SCP-427. 治疗停止了."
schinese.you_feel_healthy = "你感觉很健康"
schinese.exp = " 经验值"
schinese.evac_start = "警告！Alpha 核弹头已被激活！"
schinese.ntf_enter = "机动特遣队 Epsilon-11 九尾狐 已进入设施"
schinese.beta7_enter = "机动特遣队 Beta-7 疯帽商 已进入设施"
schinese.nu7_enter = "机动特遣队 Nu-7 落锤 已进入设施"
schinese.eta10_enter = "机动特遣队 Eta-10 非礼勿视 已进入设施"
schinese.goc_enter = "全球超自然联盟攻击小组已入侵设施!"
schinese.fbi_enter = "联邦调查局所属特异事故处已入侵设施!"
schinese.unknown_enter = "未知武装已入侵设施"
schinese.evac_15min = "注意！距离 Alpha 核弹头引爆还有 15 分钟！"
schinese.decont_5min = "注意！轻收容区将在 5 分钟后开始净化清除程序。"
schinese.decont_1min = "注意！轻收容区将在 1 分钟后开始净化清除程序！"
schinese.evac_10min = "注意！距离 Alpha 核弹头引爆还有 10 分钟！"
schinese.evac_5min = "注意！距离 Alpha 核弹头引爆还有 5 分钟！"

--PROGRESS BAR
schinese.progress_wait = "等待中..."
schinese.bismillah = "阅读祷文中..."
schinese.repairing_generator = "维修发电机中..."
schinese.picking_up_docs = "收集文件中..."
schinese.medkit_healing = "治疗中"
schinese.hacking_door = "骇入中..."
schinese.ressurecting_someone = "复活中..."
schinese.opening_car_door = "开门中..."
schinese.progress_using = "使用中..."
schinese.hacking_cell = "破坏挡板中..."
schinese.cannibal = "吃尸体中..."
schinese.checking_class = "检查身份中..."
schinese.disarming = "缴械中..."
schinese.creating_zombie = "治愈中..."
schinese.drinking_blood = "饮血中..."
schinese.sprint = "冲刺"
schinese.ragemode = "狂暴"
schinese.throwing_grenade = "投掷手榴弹"
schinese.scp939_eating_body = "享用美味中..."
schinese.scp999_healing = "治疗中..."
schinese.stealing = "偷窃中..."
schinese.giving_uniform = "给予制服中..."
schinese.changing_identity = "更改身份中..."
schinese.becoming_invisible = "消失不见中..."
schinese.giving_equipment = "给予装备中..."
schinese.blocking_door = "锁门中..."
schinese.interrogation = "审讯中..."
schinese.breaking_door = "破门中..."
schinese.looting_trash_can = "搜索垃圾桶中..."
schinese.progress_stopped = "停止!"
schinese.looting_body = "搜索中..."
schinese.progress_done = "完成！"

--ARMORS
schinese.armor_medic = "医疗人员制服"
schinese.armor_mtf = "机动特遣队制服"
schinese.armor_sci = "研究人员制服"
schinese.armor_sci_assistant = "初级研究员制服"
schinese.armor_sci_senior = "高级研究员制服"
schinese.armor_goc = "GOC 装甲"
schinese.armor_chaos = "混沌分裂者制服"
schinese.armor_hazmat_blue = "蓝色防化服"
schinese.armor_hazmat_orange = "橙色防化服"
schinese.armor_hazmat_white = "白色防化服"
schinese.armor_hazmat_yellow = "黄色防化服"
schinese.armor_hazmat_black = "黑色防化服"
schinese.armor_lighthazmat_white = "白色轻型防化服"
schinese.armor_lighthazmat_yellow = "黄色轻型防化服"

--DISEASES
schinese.diseases_appendicitis = "急性阑尾炎"
schinese.diseases_lungcancer = "肺癌"
schinese.diseases_asthma = "哮喘"
schinese.diseases_cardiacarrest = "心脏骤停"
schinese.diseases_spontaneouscombustion = "自燃"
schinese.diseases_chickenpox = "水痘"
schinese.diseases_cold = "感冒"
schinese.diseases_musclemutation = "肌肉突变"
schinese.diseases_mitosis = "超细胞有丝分裂"

--CHAT NOTIFICATIONS
schinese.you_cant_wear_this_uniform = "你无法穿上这件衣服！"
schinese.your_current_exp = "你当前的经验值："
schinese.scp914_change_mode = "你将SCP-914的加工模式调节为："
schinese.quran_needed = "你需要拿出祷文。"
schinese.you_cant_repair_generator = "你无法修理发电机。"
schinese.you_need_toolkit = "你需要一个工具箱。"
schinese.scp294_sex = "为你找个女朋友可比登天还难。"
schinese.scp294_fanta = "这味道棒极了！"
schinese.scp294_water = "尝起来像白开水，毫无特殊之处。"
schinese.scp294_out_of_order = "SCP-294 无法制造这种液体 \""
schinese.weaponry_cant_use = "你无法与该物体互动！"
schinese.weaponry_take_ammo = "你已获得配属武器的弹药."
schinese.weaponry_took_ammo_security_pt1 = "你已经拿取过装备了！"
schinese.weaponry_took_ammo_security_pt2 = "你已获得一套制式装备。"
schinese.weaponry_took_ammo_already = "你已经拿过弹药了！"
schinese.weaponry_took_uniform_already = "你已经穿戴着装备了！"
schinese.weaponry_need_slots_pt1 = "你必须有 "
schinese.weaponry_need_slots_pt2 = " 个空的物品栏！"
schinese.weaponry_mtf_armor_pt1 = "你穿上了这套装备"
schinese.weaponry_mtf_armor_pt2 = "\"机动特遣队\""
schinese.ci_choppa_down = "你因击毁直升机而被奖励。现在立即撤离！"
schinese.gru_psycho_pt1 = "见鬼！"
schinese.gru_psycho_pt2 = "这疯子到底在干什么！？！？！？"
schinese.ctf_docs_to_base = "将机密文件运送回你的基地。"
schinese.scp1025_you_read_about = "你读到了关于 \""
schinese.scp294_nothing = "杯子里空无一物。"
schinese.scp294_bleach = "你喝了一口漂白剂。内脏剧烈灼痛，满嘴泳池消毒水味。现在祈祷你的胃能挺过致命剧毒吧。"
schinese.scp294_refreshing_drink = "清爽宜人的饮品。"
schinese.deffib_body_decayed_pt1 = "这具尸体已经完全腐烂了，"
schinese.deffib_body_decayed_pt2 = "无法复活。"
schinese.deffib_body_too_late_pt1 = "这具尸体已经死的很久了，"
schinese.deffib_body_too_late_pt2 = "无法复活。"
schinese.deffib_headshot_pt1 = "这具尸体被爆头了，"
schinese.deffib_headshot_pt2 = "无法复活。"
schinese.scp049_too_late = "这具尸体已经躺了一会了,无法被治愈"
schinese.scp049_time_out_pt1 = "可惜的是,你已经躺了一会了"
schinese.scp049_time_out_pt2 = "已无法被治愈"
schinese.scp062_new_stage_pt1 = "恭喜。"
schinese.scp062_new_stage_pt2 = "你解锁了新阶段，获得了全新能力！"
schinese.scp173_bad_zone = "你无法在此区域使用技能。"
schinese.scp939_look_on_body = "你必须看着尸体才能食用！"
schinese.scp999_healthy = "他非常健康."
schinese.thief_look_on_them = "你必须看着目标才能窃取物品。"
schinese.thief_cant_steal = "你无法从该玩家身上窃取此物品！"
schinese.thief_need_slot = "你的背包已经满了."
schinese.thief_has_already = "你已经拥有此物品了！"
schinese.uiuspy_doc_dist_pt1 = "距离\'心上人\'有:"
schinese.uiuspy_doc_dist_pt2 = "大概"
schinese.cicommander_conscripted_already = "目标已经有装备了."
schinese.cicommander_need_to_take_off_smth = "目标需要脱下装备."
schinese.cicommander_no_slots = "目标的背包中必须有空余栏位。"
schinese.feelon_no_ground = "地雷必须部署在地面上！"
schinese.feelon_too_far = "看起来,你离你想放地雷的地方太远了."
schinese.engi_no_ground = "炮塔必须部署在地面上！"
schinese.hitman_take_off_helmet = "脱下头盔。"
schinese.hitman_take_off_vest = "脱下防弹背心！"
schinese.hitman_disguised = "你成功更换了你的服装!"
schinese.strong_no_ground = "你必须站在平稳的地面上。"
schinese.mtf_security_need_supplies = "在使用此技能前，你需要先从军械柜中获取装备！"
schinese.abilities_name_seccaptain = "分发安保制服"
schinese.abilities_seccaptain = "为一名幸存者分发安保新兵制服。"
schinese.seccaptain_only_classd_sci = "你只能将制服分发给D级人员或科学家！"
schinese.seccaptain_success = "你已成功将安保新兵制服分发给"
schinese.seccaptain_received = "安保主管给了你一套安保制服、一把格洛克手枪（无弹药）和一张一级钥匙卡！"
schinese.seccaptain_cant_conscript_heavy = "你无法将安保制服发给具有此体型/职业的玩家！"
schinese.seccaptain_cant_conscript_spy = "你不能把安保制服发给间谍！"
schinese.seccaptain_cant_conscript_tester = "你不能把安保制服发给病毒学家！"
schinese.strong_look_on_them = "你必须看着目标."
schinese.strong_look_on_them1 = "你需要看着目标才能擒拿."
schinese.uiuspec_look_on_button = "你必须对准门禁按钮！"
schinese.became_invisible = "技能激活，你现在处于隐形状态。"
schinese.commitee_look_on_them = "请对准目标！"
schinese.commitee_cant_conscript = "你无法为此玩家提供装备！"
schinese.commitee_no_slots = "该玩家的装备库存中必须有空闲格!"
schinese.commitee_active_weapon = "该玩家必须将物品从手中拿开!"
schinese.ulx_still_alive = " 还活着"
schinese.arena_participating = "你正在参与角斗竞技场"
schinese.arena_left = "你离开了竞技场"
schinese.ulx_ability_not_found_pt1 = "能力"
schinese.ulx_ability_not_found_pt2 = "未找到。"
schinese.ulx_family_sharing_pt1 = "玩家"
schinese.ulx_family_sharing_pt2 = "未使用 Steam 家庭共享。"
schinese.ulx_family_sharing_pt3 = "正在使用 Steam 家庭共享，主号 SteamID64"
schinese.ulx_never = "永不过期。"
schinese.ulx_after = "剩余"
schinese.ulx_not_gagged = "该玩家未被禁麦。"
schinese.ulx_gagged_by = "被管理员惩罚"
schinese.ulx_gag_reason = "理由"
schinese.ulx_gag_expires = "禁麦到期时间"
schinese.ulx_not_muted = "这个玩家没有被禁言."
schinese.ulx_muted_by = "被管理员禁言"
schinese.ulx_mute_reason = "理由"
schinese.ulx_mute_expires = "禁言到期时间"
schinese.ulx_global_banned = "已成功封禁。"
schinese.ulx_global_unbanned = "已解封玩家"
schinese.ulx_has_been_muted = "已被限制文字聊天权限："
schinese.ulx_has_been_muted_for = "被剥夺文字聊天权限，时长："
schinese.ulx_has_been_muted_permanently = "已被永久禁止文字聊天"
schinese.ulx_has_been_muted_by = "执行人"
schinese.ulx_you = "（你）"
schinese.ulx_player = "玩家"
schinese.ulx_has_been_gagged = "已被限制语音聊天权限："
schinese.ulx_has_been_gagged_for = "被剥夺语音发言权限，时长："
schinese.ulx_has_been_gagged_permanently = "已被永久禁止语音发言"
schinese.ulx_has_been_gagged_by = "执行人"
schinese.ulx_prioritysupport = "当前排队优先权："

schinese.ulx_premium_expired = "你尚未开通高级会员资格。"
schinese.ulx_premium_will_expire_pt1 = "你的"
schinese.ulx_premium_will_expire_pt2 = "高级会员资格"
schinese.ulx_premium_will_expire_pt3 = "到期剩余时间："

schinese.ulx_admin_expired = "你没有管理员权限。"
schinese.ulx_admin_will_expire_pt1 = "你的"
schinese.ulx_admin_will_expire_pt2 = "管理员权限"
schinese.ulx_admin_will_expire_pt3 = "到期剩余时间："

schinese.ulx_has_been_successfully_muted = "已被成功禁言。"
schinese.ulx_has_been_successfully_gagged = "已被成功禁麦。"
schinese.ulx_admin = "管理员"
schinese.ulx_they_removed_mute_from_you = "为你解除了文字禁言。"
schinese.ulx_has_been_sucessfully_unmuted = "已恢复文字发言权限。"
schinese.ulx_they_removed_gag_from_you = "为你解除了语音禁麦。"
schinese.ulx_has_been_sucessfully_ungagged = "已恢复语音发言权限。"
schinese.ulx_unignore = "你现在可以听到"
schinese.ulx_ignore = "你现在听不到"
schinese.ulx_your_mute_expired = "处罚期已过，你的文字聊天已解禁。"
schinese.ulx_your_gag_expired = "处罚期已过，你的语音聊天已解禁。"
schinese.ulx_asay_cd = "你必须等待 30 秒才能再次向管理员发送消息。"
schinese.player = "玩家"
schinese.unlocked_achievement = "解锁了成就"
schinese.scp860_first_msg = "你 \"SCP-860-2\" 在你的森林中"
schinese.scp860_second_msg = "你能看到墙上的出口"
schinese.loudconnect_connecting = "全体注意! 超级进服播报!"
schinese.loudconnect_carpet = ",全场掌声雷动! 铺红地毯迎接！"
schinese.loudconnect_hooray = ",演播室全员起立欢呼！好耶！"
schinese.evac_disclosed = "你真倒霉,你的身份被安保人员查了出来,你被送到了接近南西伯利亚的贝加尔湖的一片区域"
schinese.dont_spawncamp = "你个[数据删除]!不去执行任务,在这里摸鱼？"
schinese.gru_task = "你的首要目标："
schinese.pmfrom = "私聊来自："
schinese.scp_occupied_pt1 = "项目"
schinese.scp_occupied_pt2 = "已被其他玩家选用。请另选一个 SCP。"
schinese.temp_attach = "枪械配件改装时间仅限 30 秒。"
schinese.temp_attach_time_out = "改装时间已耗尽。"
schinese.uiuspy_docs_ready = "干得好,需要的情报已经全部被上传,你的新任务是带着情报逃离设施,别忘了妥善使用你的钥匙卡!"
schinese.premium_2x_bonus_pt1 = "由于你拥有"
schinese.premium_2x_bonus_pt2 = "高级会员"
schinese.premium_2x_bonus_pt3 = "身份"
schinese.premium_2x_bonus_pt4 = "你所获取的经验值已翻倍结算。"
schinese.levelup = "恭喜，你升级了！当前等级："
schinese.premium_unlocked_pt1 = "你已激活高级会员，有效期："
schinese.premium_unlocked_pt2 = " 天！"
schinese.player_connected = "加入了服务器"
schinese.player_connected_first_time = "加入服务器，这是他首次来到这里！"
schinese.player_connected_with_new_name = "加入了服务器，他曾用名为"
schinese.prefix_unlocked = "你已解锁专属前缀权限！"
schinese.levels_gifted_pt1 = "你获得了"
schinese.levels_gifted_pt2 = " 级！"
schinese.sins_cleansed = "你所有的警告记录均已被撤销！"
schinese.you_are_not_supposed_to_be_here_pt1 = "警告,你不应该出现在这里!如果你在 5 秒内不离开,"
schinese.you_are_not_supposed_to_be_here_pt2 = "你将被就地处决！"
schinese.premium_expired = "你的VIP已过期,你可以选择延长VIP,请访问相关QQ群了解更多信息."
schinese.not_enough_players = "在线玩家人数不足，正在等待更多人员……"
schinese.game_will_start_soon = "游戏将在 2 分钟后开始！"
schinese.not_enough_players_for_round_start = "人数未达回合开启标准，等待人员进入……"
schinese.you_are_muted = "你已被禁言。"
schinese.no_radio = "你身上没有对讲机！"
schinese.turn_up_the_radio = "请先开启对讲机！"
schinese.no_text_radio = "请输入文字！"
schinese.radio_in_chat = "[对讲机]"
schinese.gru_friendly = "友军支援已抵达：格鲁乌\"P\"部门"
schinese.looting_started = "你开始搜刮尸体，需要花费一些时间……"
schinese.looting_end = "搜刮完成！"
schinese.looted_ammo_pt1 = "你拿了"
schinese.looted_ammo_pt2 = "弹药"
schinese.sport_run = "改变奔跑速度为快"
schinese.default_run = "改变奔跑速度为普通"
schinese.cant_change_run = "无法切换奔跑速度"
schinese.spyusainfo = "提示：如果你无法接近刺杀目标，可以尝试黑入主控终端。但这会触发警报，请务必小心。"
schinese.spyusa_toolate_for_hacking = "骇入为时已晚,任务失败,当前主要目标:逃离设施."
schinese.spyusa_toolate_for_hacking_document = "你发送了设施坐标给UIU,但为时已晚,支援来不及到达. 任务失败. 当前主要目标:逃离设施."
schinese.spyusa_hofnotdead = "设施主管目前仍然活着。"
schinese.spyusa_hacking = "启动骇入过程..."
schinese.spyusa_hacking_notify = "所有人员注意:控制终端检测到非法强硬访问手段!"
schinese.spyusa_hacking_successful = "你成功入侵了终端,并将设施坐标发送给UIU,你重新刷新了你的钥匙卡,现在它能够开启大门."
schinese.spyusa_hacking_stopped = "尝试骇入已被阻止!"
schinese.spyusa_enemy_detected = "在降落区附近侦测到敌对武装活动，支援抵达延迟一分钟"

--TEAMS
schinese["Not Set"] = "null"
schinese["SCPs"] = "SCP"
schinese["MTF Guards"] = "机动特遣队"
schinese["Class-Ds"] = "D级人员"
schinese["Spectators"] = "观察者"
schinese["Scientists"] = "科研部门"
schinese["Chaos Insurgency"] = "混沌分裂者"
schinese["Security Department"] = "安保部门"
schinese["GRU"] = "格鲁乌\"P\"部门"
schinese["Nine Tailed Fox"] = "机动特遣队 Epsilon-11“九尾狐”"
schinese["Serpents Hand"] = "蛇之手"
schinese["Global Occult Coalition"] = "全球超自然联盟"
schinese["Unusual Incidents Unit"] = "特异事故处"
schinese["Quick Response Team"] = "快速反应部队"
schinese["Children of the Scarlet King"] = "深红王之子"
schinese["Specials"] = "特殊科研"
schinese["Spec. Task Force"] = "特别任务小队"
schinese["Nazi Germany"] = "纳粹德国"
schinese["American Army"] = "美军"
schinese["Arena Participants"] = "角斗场选手"

--SCOREBOARD
schinese.scoreboard_ping = "延迟"
schinese.scoreboard_level = "等级"
schinese.scoreboard_achievements = "成就"
schinese.scoreboard_country = "国家/地区"
schinese.scoreboard_score = "分数"
schinese.scoreboard_rounds_left = "剩余回合数"

--BOTTOM MESSAGES
schinese.ammo_maximum = "你的弹药已经满了."
schinese.ammo_not_suitable = "这种弹药不适配你的枪支."
schinese.scp294_feeling_really_bad = "喝完这个之后,我感到很难受 "
schinese.scp294_scp500 = "喝下去之后,感觉浑身都舒服了"
schinese.vendor_no_money = "你需要钱才能买"
schinese.vendor_bought = "你花钱买了杯喝的"
schinese.scp1025_chickenpox = "你感觉很痒"
schinese.scp1033_protect = "手镯将会保护你"
schinese.scp1033_depleted = "手镯似乎没有作用了"
schinese.screwdriver_used = "你使用了螺丝刀打开了检查点钢板"
schinese.scp409_1st_stage = "你突然感到全身冷的发抖"
schinese.scp409_2nd_stage = "突然你觉得很冷"
schinese.inventory_full = "你的背包物品栏已满"
schinese.secondary_inventory_full = "你的副物品栏已满"
schinese.trashbin_loot_end = "你完成了对垃圾桶的搜索"
schinese.trashbin_empty = "垃圾桶里空无一物。"
schinese.access_denied = "操作拒绝"
schinese.access_granted = "操作许可"
schinese.keycard_needed = "需要一张权限卡才能进行操作."

-- 记分牌
schinese.scoreboard_ping = "延迟"
schinese.scoreboard_level = "等级"
schinese.scoreboard_achievements = "成就"
schinese.scoreboard_country = "国家"
schinese.scoreboard_score = "分数"
schinese.scoreboard_rounds_left = "剩余回合数"
schinese.scoreboard_karma = "声望"
schinese.scoreboard_tag = "称号"

--DESCRIPTIONS
BREACH = BREACH || {}
BREACH.Descriptions = BREACH.Descriptions || {}
BREACH.Descriptions.chinese = BREACH.Descriptions.english || {}
BREACH.Descriptions.chinese[role.SCI_SpyUSA] = "你的目标：刺杀设施主管\n获取其门禁代码并通过主控终端呼叫支援\n尽量避免造成不必要的伤亡"
BREACH.Descriptions.chinese[role.Nazi] = "你当前的首要目标是歼灭所有美军。\n\n绝不能让他们获胜！"
BREACH.Descriptions.chinese[role.USA] = "你当前的首要目标是歼灭所有纳粹分子。\n\n绝不能让他们获胜！"
BREACH.Descriptions.chinese[SCP999] = "你的目标是逃离设施！"
BREACH.Descriptions.chinese[role.Chaos_Grunt] = "服从指挥官的命令，完成目标！"
BREACH.Descriptions.chinese[role.Chaos_Demo] = "你配有一把带两发弹药的RPG，好好利用她!\n服从指挥官的命令，完成目标！"
BREACH.Descriptions.chinese[role.Chaos_Jugg] = "你配备了M60机枪和重装护甲，为队友扫平障碍!\n服从指挥官的命令，完成目标！"
BREACH.Descriptions.chinese[role.Chaos_Commander] = "你可以招募D级人员加入混沌分裂者!\n向你的部下下达指令，完成任务！"
BREACH.Descriptions.chinese[role.NTF_Soldier] = "你的P90冲锋枪可以给SCP造成可观的伤害\n营救设施人员重新收容SCP！"
BREACH.Descriptions.chinese[role.NTF_Specialist] = "你的技能可以暂时硬控SCP\n营救设施人员重新收容SCP！"
BREACH.Descriptions.chinese[role.NTF_Sniper] = "你有一挺威力巨大的巴雷特狙击枪\n营救设施人员重新收容SCP！"
BREACH.Descriptions.chinese[role.NTF_Medic] = "服从指挥官指令，保持小队战斗力！"
BREACH.Descriptions.chinese[role.NTF_Pilot] = "你是九尾狐小队 撤离飞行员\n随时待命！"
BREACH.Descriptions.chinese[role.NTF_Commander] = "你的技能可以扫描设施内各目标的位置\n指挥你的部下完成任务！"
BREACH.Descriptions.chinese[role.Cult_Grunt] = "遵循祭司的命令并完成仪式!"
BREACH.Descriptions.chinese[role.Cult_Psycho] = "遵循祭司的命令并完成仪式!"
BREACH.Descriptions.chinese[role.Cult_Commander] = "率领并指挥教徒扫清障碍并完成仪式！"
BREACH.Descriptions.chinese[role.Cult_Specialist] = "遵循祭司的命令并完成仪式!"
BREACH.Descriptions.chinese[role.UIU_Soldier] = "听从指挥官指令，完成指定任务！"
BREACH.Descriptions.chinese[role.UIU_Specialist] = "你可以锁上任何门一段时间\n听从指挥官指令，执行破译和技术任务！"
BREACH.Descriptions.chinese[role.UIU_Clocker] = "你迅猛且致命，淬毒战刃削铁如泥，甚至足以切碎SCP!\n听从指挥官指令，完成任务！"
BREACH.Descriptions.chinese[role.UIU_Commander] = "你的毒气手雷能够对吸入的人造成大量伤害\n向你的部下下达指令，完成任务！"
BREACH.Descriptions.chinese[role.GRU_Soldier] = "服从指挥官的调遣，肃清目标！"
BREACH.Descriptions.chinese[role.GRU_Specialist] = "服从指挥官调遣，发挥战术专长！"
BREACH.Descriptions.chinese[role.GRU_Jugg] = "服从指挥官指令，用火力撕碎敌人防线！"
BREACH.Descriptions.chinese[role.GRU_Commander] = "组织并号令部属，誓死达成作战指标！"
BREACH.Descriptions.chinese[role.Goc_Grunt] = "不惜一切代价引爆 Alpha 核弹头！"
BREACH.Descriptions.chinese[role.Goc_Commander] = "你具备短时间遁形隐身的能力\n不惜一切代价引爆 Alpha 核弹头！"
BREACH.Descriptions.chinese[role.Goc_Special] = "你可以放置一个信标并在将来传送过去\n不惜一切代价引爆 Alpha 核弹头！"
BREACH.Descriptions.chinese[role.Goc_Jag] = "你能生成一面跟随你移动的能量护盾\n仅有全球超自然联盟下发的武器才能击穿它\n不惜一切代价引爆 Alpha 核弹头！"
BREACH.Descriptions.chinese[role.DZ_Grunt] = "救助并引导 SCP 实体安全撤离！"
BREACH.Descriptions.chinese[role.DZ_Gas] = "救助并引导 SCP 实体安全撤离！"
BREACH.Descriptions.chinese[role.DZ_Psycho] = "救助并引导 SCP 实体安全撤离！"
BREACH.Descriptions.chinese[role.DZ_Commander] = "你拥有释放一个可以传送至随机区域的传送门的能力\n千万小心，谁也无法预料对端是何险境……\n救助并引导 SCP 实体安全撤离！"
BREACH.Descriptions.chinese[role.QRT_Soldier] = "保卫设施主管并服从其命令！"
BREACH.Descriptions.chinese[role.QRT_Medic] = "保卫设施主管并服从其命令！"
BREACH.Descriptions.chinese[role.QRT_ShockTrooper] = "保卫设施主管并服从其命令！"
BREACH.Descriptions.chinese[role.QRT_Commander] = "指挥你的部下保卫设施主管并服从其命令！"
BREACH.Descriptions.chinese[role.QRT_Machinegunner] = "提供重装火力压制，保卫设施主管并服从其命令！"
BREACH.Descriptions.chinese[role.QRT_Shield] = "你拥有防弹盾牌\n保卫设施主管并服从其命令！"
BREACH.Descriptions.chinese[role.QRT_Marksmen] = "保卫设施主管并服从其命令！"
BREACH.Descriptions.chinese[role.OSN_Soldier] = "你是特别任务小队 战士\n\n保卫调度员并执行其下达的各项调遣！"
BREACH.Descriptions.chinese[role.OSN_Specialist] = "你是特别任务小队 战术专家\n保卫调度员并执行其指令！"
BREACH.Descriptions.chinese[role.OSN_Commander] = "你是特别任务小队 指挥官\n保卫调度员并率领小队贯彻执行命令！"
BREACH.Descriptions.chinese[role.SECURITY_Recruit] = "你是安保部门 菜鸟\n护送科学家并合力逃离设施！"
BREACH.Descriptions.chinese[role.SECURITY_Sergeant] = "你是安保部门 中士\n你可以向初阶安保人员下达指令\n全力护送科学家并活着逃出设施！"
BREACH.Descriptions.chinese[role.SECURITY_OFFICER] = "你是安保部门 警员\n护送科研人员并逃离收容失效区域！"
BREACH.Descriptions.chinese[role.SECURITY_Warden] = "你是安保部门 突击队员\n与其他安保不同，你配备了半自动速射武器\n护卫科学家并逃出设施！"
BREACH.Descriptions.chinese[role.SECURITY_Shocktrooper] = "你是安保部门 调查员\n前几天你从情报部门得到了一个绝密情报，你可以向基层警卫发布指令,\n掩护科学家突围逃离！"
BREACH.Descriptions.chinese[role.SECURITY_IMVSOLDIER] = "你是安保 特装专员\n保护科研人员并成功撤离！"
BREACH.Descriptions.chinese[role.SECURITY_Chief] = "你是安保部门 上尉\n你可以号令指挥全体安保部门成员\n护送全体科学家安全撤退！"
BREACH.Descriptions.chinese[role.SECURITY_Spy] = "你表面上：是一名安保部门见习警卫\n实际上：是伪装潜伏在基金会的混沌分裂者卧底\n想尽一切办法营救并护送 D 级人员逃出生天！"
BREACH.Descriptions.chinese[role.SCI_SPECIAL_DAMAGE] = "你是SCP处决部 凯伦博士\n你可以为周围的友军提供对 SCP 伤害加成的增益光环\n与科研同僚及警卫通力协作，逃出设施！"
BREACH.Descriptions.chinese[role.SCI_SPECIAL_HEALER] = "你是玛蒂尔达组长\n你可以为周围的同伴持续治愈伤势\n与科研同僚及警卫通力协作，逃出设施！"
BREACH.Descriptions.chinese[role.SCI_SPECIAL_SLOWER] = "你是SCP应对部门 速韦恩博士\n你可以大幅迟缓压制周围 SCP 实体的移动速度\n与同僚配合，突围撤退！"
BREACH.Descriptions.chinese[role.SCI_SPECIAL_SPEED] = "你是SCP应对部门 罗昴博士\n你可以为身边的人员大幅提升机动奔跑速度\n与同僚及警卫紧密抱团，逃出设施！"
BREACH.Descriptions.chinese[role.SCI_SPECIAL_MINE] = "你是SCP处决部 费罗恩博士\n你能够布设特殊的反 SCP 异能地雷\n与队友协作反制异常，逃离生天！"
BREACH.Descriptions.chinese[role.SCI_SPECIAL_BOOSTER] = "你是格奥尔格博士\n你具备全面强化周围友军综合身体机能的强化能力\n协助同伴，共同脱离险境！"
BREACH.Descriptions.chinese[role.SCI_SPECIAL_SHIELD] = "你是谢梅尔博士\n你能够撑起抵御子弹射击的防护能量盾\n抵御武装交火，掩护人员逃离！"
BREACH.Descriptions.chinese[role.SCI_SPECIAL_INVISIBLE] = "你是鲁普雷希特博士\n你可以施展让自身与临近同伴一并隐形的特殊力场\n神不知鬼不觉地躲过猎杀，逃离设施！"
BREACH.Descriptions.chinese[role.SCI_SPECIAL_VISION] = "你是海德薇教授\n透过特制透镜眼镜，你能洞察并透视全场所有 SCP 实体的具体动向\n指引大家避开危险，逃出设施！"
BREACH.Descriptions.chinese[role.SCI_SPECIAL_10] = "你是奥斯瓦尔德博士\n与科研同僚及警卫通力协作，逃离收容失效设施！"
BREACH.Descriptions.chinese[role.SCI_Assistant] = "你是初级科研助理\n紧跟资深学者与武装守卫，竭尽全力逃出生天！"
BREACH.Descriptions.chinese[role.SCI_SpyDZ] = "你是蛇之手 间谍\n你真实身份是伪装成科研人员的“蛇之手”渗透者\n\n尽可能掠夺并搜集高价值 SCP 项目，掩护并协助收容物们逃脱生存！"
BREACH.Descriptions.chinese[role.SCI_Grunt] = "你是科研人员\n与同僚及安保人员通力协作，逃离设施！"
BREACH.Descriptions.chinese[role.SCI_Tester] = "你是病毒学家\n依靠自身学识与保安的掩护，逃出收容失效区！"
BREACH.Descriptions.chinese[role.SCI_Recruiter] = "你是道德伦理检察官\n你具有将 D 级人员整编为科研助理的权威能力\n与其他人通力配合，逃离设施！"
BREACH.Descriptions.chinese[role.SCI_Medic] = "你是医生\n救治伤患，与警卫合作，逃离这片人间炼狱！"
BREACH.Descriptions.chinese[role.SCI_Cleaner] = "你是清洁工\n想尽一切办法与大部队汇合并逃出设施！"
BREACH.Descriptions.chinese[role.SCI_Head] = "你是科研主管\n指挥科研人员，在安保掩护下离开设施！"
BREACH.Descriptions.chinese[role.ClassD_Default] = "你是D级人员\n与其它 D 级同伴联合起来，在警卫的枪口与 SCP 的屠戮下拼死逃出生天！"
BREACH.Descriptions.chinese[role.ClassD_GOCSpy] = "你是全球超自然联盟 特工\n你伪装成了一名D级人员潜伏于此\n\n在入口区找到联盟的装备，启动Alpha核弹头！"
BREACH.Descriptions.chinese[role.ClassD_FartInhaler] = "你是D级人员……因常年被迫与各路彪形大汉挤在狭窄牢房，你的嗅觉神经早已彻底麻木坏死\n如今，哪怕致命的毒气也休想动你分毫。\n\n明智地利用这一特殊生理优势活下去吧。"
BREACH.Descriptions.chinese[role.ClassD_Pron] = "你是D级人员 小偷\n你趁研究员不备，偷偷顺走了一张宝贵的钥匙卡\n\n与其他同伴协作，逃出生天！"
BREACH.Descriptions.chinese[role.ClassD_Thief] = "你是D级人员 神偷\n凭借精湛的妙手空空绝技，你可以暗中扒窃其他人的随身贵重装备\n巧取物资，逃脱收容区！"
BREACH.Descriptions.chinese[role.ClassD_Fat] = "你是D级人员 胖逼\n魁梧肥胖的体格既为你带来了抗击打优势，也带来了一些敏捷劣势\n与狱友协作，逃出牢笼！"
BREACH.Descriptions.chinese[role.ClassD_Bor] = "你是D级人员 摔跤手\n服刑期间你从未虚度光阴，练就了一身钢筋铁骨与爆发蛮力\n与其他同伴协作，杀出一条生路！"
BREACH.Descriptions.chinese[role.ClassD_Hack] = "你是D级人员 黑客\n依靠私下自制的简陋骇入工具，你能够破解并开启各类安全门锁\n与其他人员协作，成功脱逃！"
BREACH.Descriptions.chinese[role.ClassD_Cannibal] = "你是D级人员 食人魔 \n暗无天日的收容生活彻底逼疯了你，饥渴使你甚至能生吞死尸以恢复精力……\n与其他人员配合或自寻生路，逃离设施！"
BREACH.Descriptions.chinese[role.ClassD_Probitiy] = "你是D 级人员 大兜哥\n你的口袋似乎比旁人更加深邃宽大，能随身暗藏更多物资\n与其他 D 级人员通力协作，逃出设施！"
BREACH.Descriptions.chinese[role.ClassD_Sportsman] = "你是D 级人员 运动员\n你的奔跑速度远超常人\n穿梭在危机四伏的走廊中，逃出生天！"
BREACH.Descriptions.chinese[role.ClassD_Killer] = "你是D级人员 杀手\n你精通夺人性命的冷酷格斗技巧\n除掉阻碍你的人，逃出牢笼！"
BREACH.Descriptions.chinese[role.ClassD_Hitman] = "你是D级人员 职业杀手\n你曾是身手不凡的职业刺客，老本行的伪装与杀戮技巧未曾生疏半分……\n伪装潜伏，逃出生天！"
BREACH.Descriptions.chinese[role.MTF_Guard] = "你是机动特遣队 士兵\n服从各级指挥官调度，完成任务！"
BREACH.Descriptions.chinese[role.MTF_Medic] = "你是机动特遣队 医疗兵\n服从长官命令，保障队员的生存与推进！"
BREACH.Descriptions.chinese[role.MTF_Left] = "严格执行高层指令，向部下下达作战任务\n收容异常，控制局面！"
BREACH.Descriptions.chinese[role.MTF_Chem] = "你穿戴有全套重装防化生化服\n你完全免疫轻收容区的净化消毒毒气，且对 SCP-409 晶化拥有天然抗性\n服从命令，完成任务！"
BREACH.Descriptions.chinese[role.MTF_Shock] = "你是机动特遣队 突击队员，随身携带有大威力燃烧弹\n听从指挥官命令，完成任务！"
BREACH.Descriptions.chinese[role.MTF_Specialist] = "你是机动特遣队 战斗专家，配备了强力的“Blackout”步枪\n听从指挥官命令，肃清所有威胁！"
BREACH.Descriptions.chinese[role.MTF_Com] = "你是机动特遣队 安全主管，有权向中尉及全体士兵发号施令\n贯彻设施主管指示，重新控制设施！"
BREACH.Descriptions.chinese[role.MTF_Engi] = "你配有对 SCP 专用重型自动哨戒炮\n抢修全部 5 台发电机以重启全设施电力\n完成任务！"
BREACH.Descriptions.chinese[role.MTF_HOF] = "你是设施主管 \n除支援特遣队外，全场所有安保与科研人员均受你直接调遣\n完成职责目标"
BREACH.Descriptions.chinese[role.MTF_Security] = "你是内部安全代理\n你拥有鉴别目标人员真实阵营归属的测谎破谎特权\n肃清内奸与间谍，完成任务！"
BREACH.Descriptions.chinese[role.Dispatcher] = "你是调度员\n和机动特遣队，并在危急关头呼叫快速反应部队支援！"
BREACH.Descriptions.chinese[role.MTF_Jag] = "你是机动特遣队 重装\n以钢铁之躯为全队扫平障碍，消灭敌对力量！"

--CHATPRINT
schinese.sgoc_first_objective = "你找到了装备,进行主要目标任务开启核弹."
schinese.ammocrate_max_ammo = "你不能为这种类型的武器补充已达到上限."
schinese.ammocrate_no_ammo = "弹药箱里已经没有这种武器的弹药了"
schinese.ammocrate_weapon_needed = "把需要弹药的武器拿出来."
schinese.cultbook_ritual_distrupted = "仪式被打断了,你需要重新开始"
schinese.cultbook_ritual_stopped = "未知对象的入侵被打断!"
schinese.cultbook_ritual_start_pt1 = "警告!未知对象正在入侵我们的现实!"
schinese.cultbook_ritual_start_pt2 = "设施武装力量接到新任务:阻止入侵!"
schinese.generator_toolkit_abuse = "你没有工具来修理发电机."
schinese.temp_attach_avaliable_pt1 = "武器配件改装台已就绪！按键"
schinese.temp_attach_avaliable_pt2 = "以开启武器配件改装面板。"
schinese.temp_attach_zone_left = "你离开了改枪范围."
schinese.uiu_remaining_computers = "已收到数据.待破解的计算机:"
schinese.uiu_mission_complete = "所有需要的数据已发送给技术部门,现在快速逃离设施!"
schinese.scp294_nospawn_destructive = "喝下这玩意儿非得把这儿夷为平地不可。我才不喝！"
schinese.scp294_nospawn_bad_idea = "这绝对是个糟糕透顶的蠢主意！"
schinese.take_off_nvg_first = "请先摘下当前戴着的夜视仪。"
schinese.radio_edit_info = "按下“鼠标右键”进入无线电频段手动设置模式。"
schinese.radio_entered_edit = "你已进入无线电手动调频模式。请按照标准格式输入（例：NNN.N，N为0-9自然数）。"
schinese.radio_exit_info = "按“鼠标右键”不保存并退出；按“ENTER”确认修改。"
schinese.radio_bad_channel = "抱歉，电台调频失败。请务必遵守规范的输入格式。"
schinese.scp109_reloading = "请稍候，SCP-109 正在自行充能。"
schinese.scp109_reload_when_pt1 = "饮用功能将在"
schinese.scp109_reload_when_pt2 = "秒后就绪。"
schinese.scp268_reloading = "请稍候，SCP-268 处于充能冷却中。"
schinese.scp268_reload_when_pt1 = "隐形效果将在"
schinese.scp268_reload_when_pt2 = "秒后才可以使用"
schinese.scp268_activated_first_pt1 = "隐形已激活。请务必避免与他人发生肢体碰撞接触，否则隐身会被立即打破。"
schinese.scp268_activated_first_pt2 = "切换武器同样会导致遁形失效；隐身效果将在 20 秒后结束。"
schinese.scp268_activated = "隐身已激活。持续时间：20 秒。"
schinese.scp268_end = "隐形遮蔽效果已解除。"
schinese.scp106_ghost_pt1 = "激活模式 \"潜行\"."
schinese.scp106_ghost_pt2 = "你的移动速度已显著提升。"
schinese.scp106_ghost_pt3 = "在此形态下你无法攻击他人，普通人类也无法目击到你。"
schinese.scp106_ghost_pt4 = "按下“R”键可随时退出该模式，你的真身将在此位置直接实体化显现。"
schinese.scp106_dimension_pt1 = "你已回到属于你的口袋次元维度。"
schinese.scp106_dimension_pt2 = "按下“H”键可回到你最初步入口袋次元的锚定位置。"
schinese.scp106_dimension_pt3 = "按下“T”键可传送到口袋空间的随机位置。"
schinese.scp106_ghost_bad_pos = "你无法在此位置退出\"潜行\"虚化模式。"
schinese.scp173_not_in_los = "你已不在本体石像的视线范围内。"
schinese.scp973_frenzy = "现在你可以按“T”键进入狂暴暴走模式"
schinese.teamkill_killed = "杀死"
schinese.teamkill_you_have_been_teamkilled = "你被队友杀死了"
schinese.teamkill_report_if_rulebreaker = "如果你觉得你被杀存在疑问,那么你可以在聊天栏输入@+内容举报"
schinese.teamkill_you_teamkilled = "你杀了一个队友"
schinese.you_have_been_killed = "击杀你的是:"
schinese.evac_start_leave_immediately = "注意,设施紧急疏散已经开始,立即离开设施!"
schinese.medkit_heal_ended = "治疗完成,你的健康状况已恢复."
schinese.demo_stop = "由于执行游戏热更新，DEMO录制已自动终止。"

--STATISTICS
schinese.apc_destroyed = "摧毁APC"
schinese.sgoc_first_objective_completed = "已完成首阶段目标"
schinese.activated_warhead = "已启动 Alpha 核弹头"
schinese.escaped = "逃脱成功"
schinese.top_docs = "获取机密绝密档案"
schinese.detonated_warhead_for_non_goc = "强行引爆 Alpha 核弹"
schinese.scp914_death = "因 SCP-914 加工致死"
schinese.repair_bonus = "修复发电机"
schinese.choppa_bonus = "摧毁撤离直升机"
schinese.cotsk_summon_bonus = "王临天下..."
schinese.uiu_obj_bonus = "目标完成"
schinese.sh_scps_stolen = "窃取SCP物品"
schinese.sh_scps_evacuated = "护送 SCP 实体成功撤离"
schinese.scp009_death = "死于 SCP-009 红冰感染"
schinese.checker_bonus = "成功甄别并揪出内鬼间谍"
schinese.scp999_healing_bonus = "治疗奖励"
schinese.psycho_bravery_bonus = "死战狂热"
schinese.interrogated_by_gru = "格鲁乌审讯嘉奖"
schinese.teamkill = "友军伤害击杀"
schinese.pacifist = "和平主义者"
schinese.enemykill = "消灭敌对目标"
schinese.headshot = "爆头击杀"
schinese.scpkill = "异常实体成功处决"
schinese.death = "阵亡"
schinese.ci_classd_evac = "护送 D 级人员成功撤离"
schinese.cheemer_rescue = "营救狗子:)"
schinese.ci_scp_evac = "带走最重要的 SCP"
schinese.sci_evac = "护送科研人员撤离"
schinese.vip_evac = "撤离站点VIP人员"
schinese.escape_fail = "撤离失败"
schinese.survival_bonus = "顽强生还奖励"
schinese.scp409_death = "死于 SCP-409 晶体化"
schinese.prem_bonus = "高级会员结算加成"

--ENDING HUD
schinese.ending_tp_to_unknown_loc = "被空间折跃至未知之地。"
schinese.ending_evac_apc = "乘坐APC撤离脱困。"
schinese.ending_ci_evac_apc_pt1 = "乘坐装甲车成功撤离，并解救了"
schinese.ending_ci_evac_apc_pt2 = "名 D 级人员。"
schinese.ending_ci_evac_apc_pt2_many = "名 D 级人员。"
schinese.ending_evac_choppa = "乘坐直升机离开SITE19成功撤离。"
schinese.ending_captured_by_unknown = "被未知身份的小队俘虏。"
schinese.ending_escaped_site19_got_captured = "逃出 Site-19 随后惨遭俘获【数据删除】"
schinese.ending_mission_complete = "任务完成."
schinese.ending_mission_failed = "任务失败."
schinese.ending_escaped_site19 = "成功逃离 Site-19。"
schinese.ending_car = "在 48 号道口发现车辆踪迹。"
schinese.ending_o5 = "对象使用了 \"特殊的方法\" O5紧急..单轨列车逃跑."

--VOICE/TEXT CHAT
schinese.whispers = "低语"
schinese.talks = "说话"
schinese.asks = "询问"
schinese.yells = "大叫"
schinese.players_online = "在线玩家"
schinese.speaks = "正在发言……"
schinese.talks_to_you = "（对你说）"
schinese.chat_unknown = "未知"
schinese.intercom = "（全域广播）"
schinese.copy_message = "复制内容"
schinese.clientside_mute = "静音"
schinese.motivational_mute = "励志语录静音"
schinese.clientside_mute_spec_only = "你只能在旁观者模式或扮演 SCP 时静音其他玩家。"
schinese.motivation_1 = "坚持下去，你已经做得很棒了!"
schinese.motivation_2 = "跨过眼前的山岳，让所有人见证你的力量!"
schinese.motivation_3 = "摒除杂念，动手去做!"
schinese.motivation_4 = "种瓜得瓜,种果得果,永远做最好的自己!"
schinese.motivation_5 = "从哪里跌倒就从哪里爬起来!"
schinese.motivation_6 = "经历的困厄越深，得来的胜利便越光辉!"
schinese.motivation_7 = "忘却失误之苦，谨记教训之重!"
schinese.motivation_8 = "要么你去主宰生活的节奏，要么就被生活所驱使!"
schinese.motivation_9 = "无需妄图一天内掌握整个人生，慢慢来!"
schinese.motivation_10 = "用饱满的热忱去拥抱每一个清晨!"
schinese.motivation_11 = "你生来坚强、无畏，且独一无二!"
schinese.motivation_12 = "实现目标所需要的一切潜能，早已深植于你的心中!"
schinese.motivation_13 = "这个世界需要你!"

--MENU
schinese.menu_scp_hud_left = "在左下角展示 SCP 技能面板"
schinese.menu_killfeed = "在观察者,显示击杀信息(右上角)"
schinese.menu_drawlegs = "第一人称渲染双腿"
schinese.menu_changelog = "更新日志"
schinese.menu_lead = "总负责人"
schinese.menu_dev = "开发者"
schinese.menu_coder = "程序员"
schinese.menu_modeller = "模型师"
schinese.menu_head_admin = "首席管理员"
schinese.menu_settings = "游戏设置"
schinese.menu_weapon_fov = "武器视场距 (度数)"
schinese.menu_weapon_z_offset = "武器垂直 Z 轴偏移"
schinese.menu_no_role_desc = "关闭开局职业介绍文本"
schinese.menu_spawn_as_sup = "以支援增援角色生成"
schinese.menu_useability = "职业技能热键"
schinese.menu_inventory_key = "打开背包键"
schinese.menu_lean_left = "左侧探头"
schinese.menu_lean_right = "右侧探头"
schinese.menu_lang = "语言选择"
schinese.menu_chat_voice = "文本与语音聊天"
schinese.menu_gradient_voice = "渐变色语音图标"
schinese.menu_voice_show_alive = "显示存活玩家状态"
schinese.menu_disable_flashes = "关闭全屏闪烁特效"
schinese.menu_disable_avatars = "关闭玩家头像"
schinese.menu_roundavatars = "圆形头像（掉帧时建议关闭）"
schinese.menu_clearemoji = "清空表情缓存文件夹"
schinese.menu_clear_downloaded_images = "清空下载图片缓存"
schinese.menu_audio = "音频设置"
schinese.menu_mute_spec = "屏蔽旁观者语音"
schinese.menu_mute_spec_if_alive = "自己处于旁观时屏蔽活人发言"

schinese.menu_music_volume = "音乐音量"
schinese.menu_music_title = "背景音乐"
schinese.menu_overall_music_volume = "整体音量"
schinese.menu_panic_music_volume = "追逐音量"
schinese.menu_spawn_music_volume = "复活音量"
schinese.menu_ambience_music_volume = "场景音量"
schinese.menu_misc_music_volume = "杂项音效音量"

schinese.menu_announcer_volume = "广播音量"
schinese.menu_visual_settings = "视觉效果设置"
schinese.menu_hide_title = "隐藏底部名称"
schinese.menu_scp_red_vision = "扮演 SCP 时开启血色视界"
schinese.menu_screenshot_mode = "截图模式"
schinese.menu_screen_effects = "景深与锐化"
schinese.menu_hud_fps = "显示 FPS"
schinese.menu_filter_textures = "纹理过滤"
schinese.menu_filter_lightmaps = "光照贴图过滤"
schinese.menu_yellow_color_filter = "泛黄色调滤镜"
schinese.menu_blue_color_filter = "泛蓝色调滤镜"
schinese.menu_filter_outside = "在地表户外环境启用滤镜"
schinese.menu_filter_intensity = "滤镜渲染强度"
schinese.menu_special_settings = "特殊设置"
schinese.menu_chat_prefix = "聊天前缀"
schinese.menu_premium_settings = "会员设置"
schinese.menu_nick_grb_color = "昵称 RGB 颜色设置"
schinese.menu_display_premium_icon = "展示会员徽标"
schinese.menu_spawn_male_only = "仅生成男性角色模型"
schinese.menu_spawn_female_only = "仅生成女性角色模型"
schinese.menu_current_lang = "当前语言："
schinese.menu_press_any_key = "请按任意键"
schinese.menu_swap = "交换"
schinese.menu_cancel = "按“END”键取消"
schinese.menu_desc_premium = "开通特权包含：优先服务器连接通道；独占皮肤；聊天框与计分板专属高亮标识；双倍经验；专属聊天互动指令；D 级专属皮肤；SCP 优先挑选权与新 SCP 尝鲜试玩；自定义彩色昵称；专属设置选项（可隐藏列表高亮或使用独占皮肤）。"
schinese.menu_prem_status = "会员状态"
schinese.menu_days = "天"
schinese.menu_forever = "永久"
schinese.menu_other = "其他"
schinese.menu_decrease_active_warnings = "消除一次违规警告"
schinese.menu_kit_start = "「新人」礼包"
schinese.menu_kit_start_desc = "包含：月度高级会员资格；直升 15 级（在当前等级基础上直接追加）"
schinese.menu_1_level = "1 级"
schinese.menu_45_level = "45 级"
schinese.menu_ungag = "解禁语音麦克风"
schinese.menu_less_than_a_week = "小于一周"
schinese.menu_more_than_a_week = "大于一周"
schinese.menu_unmute = "解禁文字发言"
schinese.menu_unban = "解封"
schinese.menu_discount = "折扣"
schinese.menu_seller = "赞助客服@#@$%^(暂不可用"
schinese.precaching_resources = "正在预加载资源..."
schinese.menu_play = "加入"
schinese.menu_resume = "继续"
schinese.menu_disconnect = "断开连接"
schinese.menu_credits = "鸣谢"
schinese.menu_settings = "设置"
schinese.menu_donate = "赞助"
schinese.menu_wiki = "维基"
schinese.menu_my_life_my_rules = "服规"
schinese.menu_sure = "你确定吗？"
schinese.menu_yes = "是"
schinese.menu_no = "否"
schinese.menu_do_precache_or_nah = "要预加载内容吗？"
schinese.menu_precache_hover = "在预加载期间,你仍然有机会复活"
schinese.menu_no_precache_hover = "你仅应在加载时间大于4分钟且因此被踢出的情况下跳过预加载\n警告:游玩期间预计会有大量卡顿"
schinese.menu_quickchat = "快捷聊天"

--TASKS
schinese.tasks_evacuate_personnel_and_defend_comrades = "疏散设施,帮助队友"
schinese.tasks_escape_from_site19 = "逃离设施"
schinese.tasks_sgoc = "找到GOC装甲并引爆阿尔法弹头"
schinese.tasks_author = "AUTHOR:"
schinese.tasks_suiu = "刺杀设施主管并呼叫增援"
schinese.tasks_evacuate_personnel_and_terminate_enemies = "疏散人员,消灭SCP和D级"
schinese.tasks_coordinate_mtf_peasants = "领导自己的队员"
schinese.tasks_coordinate_mtf = "领导 MTF"
schinese.tasks_hof = "疏散设施人员并领导机动特遣队与安保部门"
schinese.tasks_mtf_checker = "疏散人员,检查人员信息"
schinese.tasks_engi = "部署防御哨戒炮塔"
schinese.tasks_help_teammates_through_intercom = "利用广播台调度并指引队友"
schinese.tasks_heal_teammates = "治疗队友"
schinese.tasks_recruitment = "招募D级"
schinese.tasks_coordinate_sci = "引导带领科研部成员"
schinese.tasks_protect_sci = "保护科学家"
schinese.tasks_help_d = "帮助D级"
schinese.tasks_help_teammates = "全力支援队友"
schinese.tasks_ntf = "收容SCP,消灭D级,疏散人员"
schinese.tasks_coordinate_ntf = "领导九尾狐部队"
schinese.tasks_skp = "屠戮消灭设施内的一切活物"
schinese.tasks_goc = "撤离前引爆阿尔法弹头"
schinese.tasks_coordinate_goc = "领导 GOC 作战部队"
schinese.tasks_gru = "根据分配任务机动处置"
schinese.tasks_coordinate_gru = "指挥格鲁乌特别分遣队"
schinese.tasks_ci = "阻止基金会人员撤离,疏散D级"
schinese.tasks_mines = "设置地雷"
schinese.tasks_coordinate_ci = "率领混沌分裂者突击力量"
schinese.tasks_osn = "掩护己方阵线，听候设施主管差遣"
schinese.tasks_coordinate_osn = "率领特别任务小队"
schinese.tasks_sh = "帮助SCP逃脱,掩护SCP"
schinese.tasks_coordinate_sh = "领导蛇之手行动"
schinese.tasks_uiu = "侵入设施电脑并且逃脱设施"
schinese.tasks_coordinate_uiu = "指挥其他UIU队员"
schinese.tasks_cotsk = "举行献祭仪式，召唤猩红之王"
schinese.tasks_coordinate_cotsk = "指挥教众"
schinese.tasks_scp999 = "治愈人类或 SCP，安全逃离"
schinese.tasks_terminate_enemies = "肃清所有敌对分子"
schinese.tasks_arena = "在角斗竞技场中战至最后"
schinese.tasks_kill_everyone_except_sh = "杀死除蛇之手之外的一切势力"
schinese.tasks_chef_sb = "指挥安保部门"

--ABILITIES
schinese.abilities_cd = "冷却："
schinese.abilities_name_thief = "两手空空"
schinese.abilities_thief = "顺走目标当前手中所持的物品！"
schinese.abilities_name_bor = "强力重击"
schinese.abilities_bor = "依靠一身蛮力直接将目标强行击倒。"
schinese.abilities_name_hitman = "完美伪装"
schinese.abilities_hitman = "当场伪装剥取你当前注视之尸体的装束外观。"
schinese.abilities_name_suiu = "\"心上人\"系统"
schinese.abilities_suiu = "能探测到\"心上人\"距离你的位置"
schinese.abilities_name_scirecruit = "招募转化"
schinese.abilities_scirecruit = "感化收编一名 D 级人员成为科研助手。"
schinese.abilities_name_cispy = "自己人!"
schinese.abilities_cispy = "知道谁是D级人员"
schinese.abilities_name_matilda = "范围治愈"
schinese.abilities_matilda = "持续大幅治愈你周围的所有同伴。"
schinese.abilities_name_speedwone = "迟滞力场"
schinese.abilities_speedwone = "严重压制周围 SCP 实体的奔跑移动速度。"
schinese.abilities_name_hedwig = "全知透视"
schinese.abilities_hedwig = "佩戴特制眼镜隔墙透视全图 SCP。"
schinese.abilities_name_feelon = "反 SCP 地雷"
schinese.abilities_feelon = "在脚下部署一枚专门压制 SCP 的高爆地雷。"
schinese.abilities_name_invis = "隐身力场"
schinese.abilities_invis = "令自己短时间彻底遁形隐身。"
schinese.abilities_name_lomao = "迅捷疾驰"
schinese.abilities_lomao = "为你自身及周围战友赋予超强移速爆发。"
schinese.abilities_name_shield = "排斥护盾"
schinese.abilities_shield = "在身旁展开一道抵御 SCP 接近的斥力防护力场。"
schinese.abilities_name_buster = "机能激发"
schinese.abilities_buster = "全方位激增你及周围同伴的基础身体机能属性。"
schinese.abilities_name_kelen = "弱点指引"
schinese.abilities_kelen = "显著提高周围友军针对 SCP 时的攻击杀伤力。"
schinese.abilities_name_engi = "哨戒防御炮"
schinese.abilities_engi = "架设一台专门索敌射杀 SCP 的全自动机枪炮塔。"
schinese.abilities_name_ntfspec = "捕捉网"
schinese.abilities_ntfspec = "直接将目标 SCP 原地定身冻结 6 秒。"
schinese.abilities_name_ntfcom = "监控网络排查"
schinese.abilities_ntfcom = "透过站点监控网络扫描指定阵营的分布位置。"
schinese.abilities_name_cicom = "分发武装"
schinese.abilities_cicom = "将 D 级人员招募装备为混沌分裂者"
schinese.abilities_name_grucom = "特种审讯"
schinese.abilities_grucom = "未提供具体说明。"
schinese.abilities_name_gocspec = "量子相位折跃"
schinese.abilities_gocspec = "布置一个折跃信标，再次激活将瞬间传送回该点。"
schinese.abilities_name_goccom = "光学迷彩"
schinese.abilities_goccom = "开启折射战衣使自己完全隐身遁形"
schinese.abilities_name_gocjag = "力场壁垒"
schinese.abilities_gocjag = "激活单向透射重防护盾，庇护你与你的小队。"
schinese.abilities_name_skpjager = "达姆弹头"
schinese.abilities_skpjager = "切换至破坏力极强的扩张性空尖开花弹头。"
schinese.abilities_name_shcom = "次元裂隙"
schinese.abilities_shcom = "撕开一处传送门，可能将你传送至站点某处，也可能导致你被卡住禁锢。"
schinese.abilities_name_uiucom = "电磁监听"
schinese.abilities_uiucom = "透视标记所有开启了无线电步话机的人员。"
schinese.abilities_name_uiuspec = "强行断门"
schinese.abilities_uiuspec = "将门控系统完全锁死瘫痪一段时间。"
schinese.abilities_name_uiuclocker = "肾上腺暴走"
schinese.abilities_uiuclocker = "爆发潜能，短时间内移速大幅狂飙。"
schinese.abilities_name_cotskpsycho = "回光返照"
schinese.abilities_cotskpsycho = "瞬间补满生命并进入狂暴，但将在 30 秒后必死暴毙。"
schinese.abilities_name_sport = "调整步频"
schinese.abilities_sport = "调整奔跑速度"

schinese.abilities_name_dzpsycho = "剧毒瓦斯弹"
schinese.abilities_dzpsycho = "投掷一枚特制瓦斯毒气弹，唯有你的防毒面具对此毒气免疫。"

schinese.abilities_name_dzsoderj = "收容洞察"
schinese.abilities_dzsoderj = "探测设施内残存的全部 SCP 物品，并向所有盟友透视标记存活 SCP 的方位。"

schinese.abilities_name_mtfspec = "声呐探测雷"
schinese.abilities_mtfspec = "布设一枚探测感应雷，只要未被摧毁，即可透过专用夜视仪透视周围敌人。"

schinese.abilities_name_chaosdemo = "阔剑定向雷"
schinese.abilities_chaosmine = "架设一枚绊发定向破片地雷，敌对人员接近时将触发致命扇形爆轰。"
schinese.chaosdemo_near_elevator = "禁止在电梯附近布设地雷！"

schinese.abilities_name_mtf_security = "身份审查"
schinese.abilities_mtf_security = "勘破目标玩家的真正阵营与潜伏身份。"

--ROLEMENU
schinese.f2_name = "姓名："
schinese.f2_objectives = "任务简报："
schinese.f2_char_stats = "角色机能属性"
schinese.f2_health = "生命值："
schinese.f2_stamina = "耐力值："
schinese.f2_choose = "请在左侧列表选中阵营与角色。"
schinese.f2_ability_name = "专属特异技能："
schinese.f2_ability_desc = "技能效用描述："
schinese.f2_ability_max = "使用次数上限："
schinese.f2_locked = "【未解锁】"
schinese.f2_unlocked = "【可选用】"
schinese.f2_req_level = "需求等级："
schinese.f2_your_level = "你当前等级："
schinese.f2_cooldown = "充能冷却"
schinese.f2_no_objectives = "暂无特殊任务目标"

schinese.f2_ntf = "机动特遣队 Epsilon-11 专司从内侧控制并保全 SCP 基金会。他们是一支训练有素的特种反应部队，专在发生特大收容失效时空降站点。其大多数部署行动均直接指向 SCP 重新收容。"
schinese.f2_chaos = "混沌分裂者是由基金会早期分裂叛逃而出的武装力量。当年一支特勤部队擅自叛离所属防区，并掠走了数件极具战略价值的异常 SCP。他们利用手中的 SCP 服务于自身的野心霸权与政治博弈。"
schinese.f2_gru = "格鲁乌“P”部门档案概览：1935 年初遵照斯大林同志密令创立，最初代号为异常事件调查委员会第四处 (CHD KAS)。其首起任务即为调查基洛夫遇刺事件。\n\n二战期间，该部整编并入新成立的格鲁乌情报总局，冠以代号“P”部门（即“心理电子与超常作战”），专事瓦解来自纳粹党卫军、祖先遗产学会 (Ahnenerbe) 与梵蒂冈教廷的异常威胁；并在冷战期间全力为苏联政府截获并深研海内外异态造物，极大程度限制了基金会在第三国际阵营领土内的行动扩张。"
schinese.f2_dz = "蛇之手是一个规模不大但极为危险且精锐的地下组织，多次恶性收容突破均有其手笔。其成员极度擅长利用异常或潜在异常物品渗透敌方腹地。他们志在解放所有受压迫的 SCP 实体。他们本意无意滥杀，但若交涉破裂，会毫不犹豫动用重型枪械；他们亦会据为己有并使用部分高危异常达成目标。"
schinese.f2_uiu = "特异事故处 (UIU) 诞生于冷战大幕拉开之初。彼时美国联邦政府极度警惕超常力量被亲苏阵营掌控。作为 FBI 的高度机密独立分支，UIU 专司对超自然恶性事件与超常犯罪作出闪电反应与行政处置。"
schinese.f2_goc = "全球超自然联盟 (GOC) 于二战废墟之上由多国联合组建。其骨干最初吸收了自纳粹帝国、苏联及盟军阵营残存流亡而出的神秘学者、通灵大师、圣职者与尖端科学家。他们以彻底毁灭超自然存在为傲，在基金会捕获收容之前，已有大批潜在 SCP 遭其彻底物理清除。"
schinese.f2_sci = "基金会科研部是支撑地下站点运作的文职中流砥柱，上至资深科学家下至基础保洁人员。尽管大多数是基金会常规雇佣的凡人，但其中不乏深藏不露之辈。资深研究员更是经验丰富、洞悉收容法则的核心智囊。"
schinese.f2_security = "安保部是维护全基金会所有前哨与 SCP 实体铜墙铁壁般防御的核心盾牌。全体安保官兵皆受过异常收容失效与抵御外敌渗透入侵的高强度特种淬炼。他们的使命不仅是保全非战斗人员免遭异常屠戮，更是防范人类自身生乱。"
schinese.f2_mtf = "机动特遣队 (MTF) 是针对特殊极端局势而临时或永久编组的精锐战术武装编队。其核心信条在于以最小代价重新建立 SCP 收容秩序并疏散关键要人，不同特遣队在各自领域拥有极高专业度。"
schinese.f2_osn = "特别任务小队——隶属于安保部直管的精锐战术编队，由专精与异常实体高危交火的战术专家及灾变动员时从各部门抽调的精干人员混编而成。其唯一信条便是在灾变爆发瞬间铁腕镇压并封堵一切逃逸的“SCP”异常物。"
schinese.f2_qrt = "快速反应部队 (QRT) 是驻扎于 Site-19 等超级站点的实验性全副武装应急机动旅。一旦发生全面收容失效或外敌突袭，站点总监或中央控制室可直接申请调派；一旦核准，全副武装的 QRT 突击群将瞬间突入地狱核心。"
schinese.f2_classd = "D 级人员是被基金会指定充当危险异常实验与高危苦役的易耗消耗人员。通常自全球各地的重刑犯、死刑犯中秘密遴选抽调。在站点发生重大灾难时，除非现场指挥官下达特赦协助令，否则原则上一律就地格杀勿论以防生乱。"
schinese.f2_cult = "猩红之王之子——这是一个由【数据删除】秘密组建、极端盲目崇拜古老毁灭神祇 SCP-001“猩红之王”的狂热异端教派。该组织系自蛇之手叛逃分离出的血腥分支。其虽然人员稀薄，但手中掌握着未经收容与解析的恐怖禁忌神器，且狂信徒自身常伴有诡异莫测的血肉异能，源头无从考证。"
schinese.f2_scp = "SCP 异常实体是基金会耗费无尽代价方得以捕获、收容并分级的超常异象与活体。它们对人类的生存延续构成不可逆的终极威胁。许多具有自主意志的 SCP 生性残虐嗜血，无时无刻不在渴望撕碎牢笼、掀起浩劫！"
schinese.f2_minigames = "用于承载各种趣味拓展与分支娱乐模式的特殊预设角色。"
schinese.f2_skp = "超常事件特别突击队 (SKP) 原系第三帝国设于二战的异常探索研究特务机关，在我们的主世界已随帝国崩溃而覆灭。但在代号 #028-DE/I2 事件中，来自 R-3378-DE 异维度的 SKP 集团竟试图横跨现实强行入侵，后被一系列偶然巧合强行挫败。SKP 抱持绝对敌意，且一旦重整旗鼓捲土重来将更为致命。若不能在萌芽期将入侵扼杀，后果将不堪设想。"

--QUICK CHAT
schinese.quickchat_request_id = "出示身份卡"
schinese.quickchat_take_off_suit = "脱下衣服"
schinese.quickchat_put_weapon_away = "收起武器"
schinese.quickchat_drop_the_weapon = "扔掉武器"
schinese.quickchat_friendly = "友军"
schinese.quickchat_run = "快跑"
schinese.quickchat_enemy_spotted = "敌人"
schinese.quickchat_scp_spotted = "SCP"
schinese.quickchat_stop = "别动"
schinese.quickchat_face_the_wall = "面朝墙壁"
schinese.quickchat_dont_follow_me = "别跟着我"
schinese.quickchat_dont_approach = "别靠近我"

--OTHER
schinese.gru_hud_task = "任务："
schinese.gru_hud_task_evacuation = "干扰撤离"
schinese.gru_hud_task_militaryhelp = "协助武装人员"
schinese.gru_hud_task_none = "无"
schinese.spectators = "旁观者"
schinese.players = "玩家"
schinese.alive = "存活"
schinese.f2_only_for_specs = "你只能在旁观模式下打开角色选单。"
schinese.machinegun_ammo = "机枪弹药"
schinese.gru_ammo = "格鲁乌机枪弹药"
schinese.smg_ammo = "冲锋枪弹药"
schinese.pistol_ammo = "手枪弹药"
schinese.revolver_ammo = "左轮弹药"
schinese.goc_ammo = "未知制式弹药"
schinese.shotgun_ammo = "霰弹枪弹药"
schinese.sniper_ammo = "狙击弹药"
schinese.body_cant_determine_death_time = "无法准确测定确切死亡时间"
schinese.body_died_right_now = "刚刚咽气死亡"
schinese.body_minutes_ago = "分钟前死亡"
schinese.body_1minute_ago = "分钟前死亡"
schinese.body_2to4minutes_ago = "分钟前死亡"
schinese.body_death_happened = "死亡发生于"
schinese.body_death_unknown = "致命死因不明"
schinese.body_unknown = "未知"
schinese.body_search = "搜刮"
schinese.body_headshot = "头部遭受毁灭性致命爆头"
schinese.body_disconnected = "未见明显暴力创伤"
schinese.body_gas = "死于吸入过量致命毒气"
schinese.body_acid = "体表有极其显著的严重强酸化学灼伤"
schinese.body_exploded = "尸身严重焦黑碳化，布满大面积破片撕裂贯穿伤"
schinese.body_fall = "双腿呈现肉眼可见的粉碎性开放性骨折"
schinese.body_crushed = "躯干多处遭受恐怖重压导致全身性开放粉碎骨折"
schinese.body_burned = "遗体大面积严重焚毁碳化"
schinese.body_slashed = "全身上下密布锐器撕裂穿刺伤"
schinese.body_low_caliber = "体表可见多处小口径枪弹射入创口"
schinese.body_high_caliber = "体表可见触目惊心的大口径反器材穿透弹孔"
schinese.body_shotgun = "体表布满密密麻麻的鹿弹霰弹创孔"
schinese.body_goc = "体表布满特种大口径穿甲杀伤创口"
schinese.body_bullets = "体表弹孔累累"
schinese.cutscene_subject = "实验对象："
schinese.cutscene_subject_name = "对象代号："
schinese.cutscene_name = "姓名："
schinese.cutscene_objective = "任务："
schinese.cutscene_disaster_relief = "无效化收容失效"
schinese.cutscene_scp_rescue = "救援并转运 SCP"
schinese.cutscene_namaz = "举行召唤仪式"
schinese.cutscene_time_after_disaster = "收容失效发生后时间："
schinese.cutscene_status = "状态："
schinese.cutscene_last_report_time = "上次联系时间："
schinese.cutscene_time_after_disaster_for_last_report_time = "收容失效后时间："
schinese.cutscene_kia = "阵亡"
schinese.cutscene_location_site19 = "地点：[未知]接近Site-19"
schinese.cutscene_evac_by_ci = "由 混沌分裂者 撤离"
schinese.cutscene_evac_by_heli = "由 直升机 撤离"
schinese.cutscene_undercover_agent = "卧底特工"
schinese.cutscene_location_site19_decon = "点位：Site-19【地表净化消杀隔离区】"
schinese.cutscene_objective_simple = "任务：遏止异常蔓延与收容重建"
schinese.cutscene_primary_obj = "> 核心任务：彻底肃清收容突破隐患，保卫 Site-19 核心区。"
schinese.cutscene_hazard_protocol = "> 生物安全状态：强制消杀净化协议运作中。"
schinese.cutscene_radio_log = "无线电通讯抄报实录"
schinese.cutscene_init_progress = "实地部署就绪"
schinese.cutscene_operative = "行动人员："
schinese.cutscene_radio_control_name = "【指挥控制中心】"
schinese.cutscene_radio_control_msg = "Site-19 报告发生收容失效"
schinese.cutscene_radio_beta7_name = "【Beta-7】"
schinese.cutscene_radio_beta7_msg = "Beta-7 小队已接手任务。"
schinese.cutscene_radio_eta10_name = "【Eta-10】"
schinese.cutscene_radio_eta10_msg = "Eta-10 小队已接手任务。"
schinese.hud_nick = "昵称："
schinese.hud_charname = "角色名："
schinese.hud_health = "生命值"
schinese.hud_health_capital = "生命值"
schinese.hud_max_level = "满级"
schinese.hud_killfeed_killed = "击杀了"
schinese.hud_killfeed_died = "阵亡"
schinese.startintro_round_will_begin = "新回合开启剩余时间："
schinese.startintro_no_round = "新回合尚未开启"
schinese.startintro_welcome_pt1 = "\nSite-19\n 欢迎莅临，"
schinese.startintro_welcome_pt2 = "\n 祝你好运！"
schinese.roundend_totaldeaths = "阵亡总人数："
schinese.roundend_escaped = "成功脱逃人数："
schinese.roundend_gameover = "对局结束"
schinese.roundend_roundcomplete = "回合结束"
schinese.roundend_roundresult = "回合结果："
schinese.roundend_roundstillrestart = "距离重启剩余局数："
schinese.roundend_nextroundin = "下一局开始倒计时："
schinese.roundend_restartinground = "正在重置战局……"
schinese.roundend_restartingserverin = "服务器将在倒计时后重启："
schinese.roundend_restartingserver = "正在重启服务器……"
schinese.roundend_scarletking = "猩红之王介入"
schinese.roundend_nopeoplealive = "无人生还"
schinese.roundend_alphawarhead = "Alpha 核弹头引爆"
schinese.roundend_alphawarheadgoc = "强行引爆 Alpha 核弹"
schinese.roundend_cbended = "收容失效已结束"
schinese.roundend_classd_win = "D 级人员 胜利"
schinese.roundend_chaos_win = "混沌分裂者 胜利"
schinese.roundend_foundation_win = "基金会 胜利"
schinese.roundend_scp_win = "SCP 胜利"
schinese.roundend_dz_win = "蛇之手 胜利"
schinese.roundend_goc_win = "全球超自然联盟 (GOC) 胜利"
schinese.roundend_cotsk_win = "猩红之王之子 胜利"
schinese.roundend_gru_win = "格鲁乌“P”部门 胜利"
schinese.roundend_uiu_win = "特异事故处 (UIU) 胜利"
schinese.roundend_draw = "平局"
schinese.take_off_hover = "点击“鼠标左键”卸下"
schinese.heavy_helmet = "重型战术防弹头盔"
schinese.heavy_armor = "重型防弹战术背心"
schinese.light_helmet = "轻便防护头盔"
schinese.light_armor = "轻量化防弹衣"
schinese.small_bag = "随身腰包"
schinese.big_bag = "战术大背包"
schinese.no_admins = "当前服务器内暂无管理员。"

schinese.shlogs_charname = "角色名"
schinese.shlogs_role = "职业"
schinese.shlogs_team = "阵营"

schinese.shlogs_setfilter = "设置筛选"

schinese.shlogs_allrounds = "全部回合"

schinese.shlogs_round = "回合"

schinese.shlogs_checksnapshot = "查看快照"
schinese.shlogs_close = "关闭"

schinese.shlogs_dead = "【已阵亡】"

schinese.shlogs_profile = "个人主页"

schinese.shlogs_details = "详细日志"

schinese.shlogs_chat = "聊天"
schinese.shlogs_chat_log1 = "玩家 sender 说：</ message \\>" -- DO NOT TRANSLATE sender, message

schinese.shlogs_death = "死亡"
schinese.shlogs_death_log1 = "玩家 victim 遭安全门夹死" -- DO NOT TRANSLATE victim
schinese.shlogs_death_log2 = "玩家 victim 被 killer 击杀" -- DO NOT TRANSLATE victim, killer

schinese.shlogs_deathelev = "电梯意外"
schinese.shlogs_deathelev_log1 = "玩家 user 因 killer 导致的电梯升降致死" -- DO NOT TRANSLATE user, victim

schinese.shlogs_icedev = "SCP(409/009) 致死"
schinese.shlogs_icedev_log1 = "玩家 user 因 killer 的 409 致死" -- DO NOT TRANSLATE user, killer
schinese.shlogs_icedev_log2 = "玩家 user 被已被 killer 杀死的 409 晶体雕像传染" -- DO NOT TRANSLATE user, killer
schinese.shlogs_icedev_log3 = "玩家 user 因 killer 的 009 致死" -- DO NOT TRANSLATE user, killer

schinese.shlogs_disconnection = "断开连接"
schinese.shlogs_disconnection_log1 = "玩家 user 断开了与服务器的连接。" -- DO NOT TRANSLATE user

schinese.shlogs_drop = "丢弃武器"
schinese.shlogs_drop_log1 = "玩家 user 丢弃了装备 weapon" -- DO NOT TRANSLATE user, weapon

schinese.shlogs_pickup = "拾取武器"
schinese.shlogs_pickup_log1 = "玩家 user 捡起了装备 weapon" -- DO NOT TRANSLATE user, weapon

schinese.shlogs_spawn = "角色生成"
schinese.shlogs_spawn_log1 = "玩家 user 已被 reviver 成功复活" -- DO NOT TRANSLATE user, reviver
schinese.shlogs_spawn_log2 = "玩家 user 作为增援部队入场生成" -- DO NOT TRANSLATE user
schinese.shlogs_spawn_log3 = "玩家 user 由管理员强制生成" -- DO NOT TRANSLATE user
schinese.shlogs_spawn_log4 = "玩家 user 于回合伊始正常生成" -- DO NOT TRANSLATE user

--[[


local min = "Minute"
local day = "Day"
local year = "Year"
local month = "Month"
local second = "Second"
local hour = "Hour"
local week = "Week"

local str = ""

for t, v in pairs(list) do

	if v == 0 then continue end

		local strtime = tostring(v)

		if v > 1 then

			if t == "m" then

				month = "Months"

				elseif t == "y" then

					year = "Years"

					elseif t == "d" then

						day = "Days"

						elseif t == "h" then

							hour = "Hours"

							elseif t == "min" then

								min = "Minutes"

								elseif t == "w" then

									week = "Weeks"

									elseif t == "s" then

										second = "Seconds"

										end
										end

										end

										]]


schinese.nt_min = "分"
schinese.nt_d = "天"
schinese.nt_y = "年"
schinese.nt_m = "月"
schinese.nt_s = "秒"
schinese.nt_h = "时"
schinese.nt_w = "周"

schinese.nt_mins = "分"
schinese.nt_ds = "天"
schinese.nt_ys = "年"
schinese.nt_ms = "月"
schinese.nt_ss = "秒"
schinese.nt_hs = "时"
schinese.nt_ws = "周"

schinese.donateadmin_protectionactivated = "紧急警告！检测到你涉嫌尝试进行恶意大规模批量封禁操作，你的管理员权限已被系统紧急冻结撤销。若系误判，请立即通过 QQ 客服通道与我们核实申诉"

schinese.desc_premium = "尊贵特权提供：以增援入场时自由挑选角色的特权（除极少数核心要职）；服务器满人排队优先插队权；计分板、公屏与语音专属亮眼徽标；全局双倍经验增幅；游戏聊天框高级专属互动指令；独家 D 级专属外观；生成为 SCP 时自由挑换 SCP 品类；更改旁观者名字专属霓虹色；独家设置面板深度定制选项"
schinese.desc_premium_plus = "包含普通会员所有特权福利；双倍经验狂飙；重生为特异科学家、快速反应部队 (QRT)、特异事故处 (UIU) 与混沌突击队时自由调换分支职业；尊享 SCP 超限定独家炫酷皮肤外观"
schinese.desc_newbiekit = "礼包内容：月度高级会员资格 + 直升 15 级（会员与 15 级原价共计 625 卢布，购买本新手礼包立省 175 卢布！）"
schinese.desc_activewarn = "销除一条处于生效期内的惩罚警告（可输入 !warns 查阅当前警告存底）"
schinese.desc_penalty = "撤销一次违规强退/逃跑惩罚记录（可输入 !checkpenalty 查验记录）"
schinese.desc_unmute = "解除游戏文字聊天封禁（如需查询禁言剩余时长，请输入 !getmuteinfo 并在其后附带你的 SteamID64）"
schinese.desc_ungag = "解除游戏语音麦克风封禁（如需查询禁麦剩余时长，请输入 !getgaginfo 并在其后附带你的 SteamID64）"
schinese.desc_unban = "解封被封账号"

schinese.desc_prefix = "赋予在游戏设置中自定义聊天个性前缀的特权。但请谨记规矩：严禁包含纳粹符号、侮辱性字眼、蓄意冒充管理或违反其它规则，否则将强制收回前缀权限。"
schinese.desc_prefix_rainbow = "赋予在设置中配置酷炫七彩渐变色动态聊天前缀的特权。同样严禁滥用、辱骂、冒充管理或触碰服规红线，违者无条件剥夺没收。"

schinese.donate_paymenttype = "> 点击此处直接跳转进入官方赞助通道网页 <"
schinese.donate_buy = "购买"

schinese.donationtitle_prem = "高级会员 (Premium)"
schinese.donationtitle_prem_plus = "至尊高级会员 (Premium+)"
schinese.donate_days = "天"

schinese.donate_other = "其他"

schinese.donate_awarn = "消除一条有效违规警告"
schinese.donate_penalty = "消除 1 次逃跑惩罚记录"

schinese.donate_newbiekit = "新人礼包"
schinese.donate_level = "等级"

schinese.donate_level_more15 = "(>15 级)"
schinese.donate_level_less15 = "(<15 级)"

schinese.donate_prefix = "前缀"
schinese.donate_gradientprefix = "渐变前缀"

schinese.donate_ltaw = "小于一周"
schinese.donate_mtaw = "超过一周"
schinese.donate_perma = "永久封禁"

schinese.desc_admin = "（！！当前暂不对外出售！！）赋予你封禁、文字禁言以及语音禁麦等管理权限。请牢记严禁滥权，一经查实将彻底永封剥夺你的管理员特权资格。"
schinese.donate_admin = "管理员"

schinese.donate_price = "价格："

schinese.donate_howmanylevels = "你要购买多少等级？"
schinese.donate_willcostyou = "售价："

schinese.donate_dragme = ">> 拖拽 <<"

schinese.scp106_ghost_pt1 = "已激活“幽灵”模式。"
schinese.scp106_ghost_pt2 = "你的移动速度已提升。"
schinese.scp106_ghost_pt3 = "在此模式下，你无法攻击任何人，其他人也无法看见你。"
schinese.scp106_ghost_pt4 = "你可以按“R”键退出该模式，你的角色将出现在当前位置。"
schinese.scp106_dimension_pt1 = "你现在处于自己的口袋维度中。"
schinese.scp106_dimension_pt2 = "按“H”键可以返回你进入口袋维度时的初始位置。"
schinese.scp106_dimension_pt3 = "按“T”键可以随机传送至任意点位。"
schinese.scp106_ghost_bad_pos = "你无法在此处退出“幽灵”模式。"

schinese.mvp_scpkill = "SCP 无效化"
schinese.mvp_headshot = "爆头"
schinese.mvp_kill = "击杀"
schinese.mvp_heal = "治疗"
schinese.mvp_damage = "伤害"

schinese.select_weapon = "选择武器"

schinese.scp049_targetisdead = "目标已死亡"
schinese.scp049_press_e = "按下“E”键治疗目标。"
schinese.scp049_press_r = "按下“R”键击杀目标（为你恢复 125 点生命值）"
schinese.scp049_targetisalive = "目标仍然存活"

schinese.supp_pick_cant = "你在当前阵营中承担着不可或缺的关键职责，无法随意更改职业。"
schinese.supp_canpick = "你已激活VIP，你可以自由更换出战职业。"
schinese.supp_pickcancel = "按下“退格键”取消挑选"
schinese.roleswap = "角色变更"

schinese.inv_throw_away = "丢弃"
schinese.load_tazer = "为泰瑟电击枪换装新电池"

schinese.select_faction_ntfcmd = "从列表中选择你要扫描的阵营。按退格键可关闭窗口。"
schinese.ntfcmd_factionlist = "阵营列表"
schinese.ntfcmd_unknowns = "未知势力"

schinese.tablet = "战术战况平板"

schinese.donate_cosmetics = "个性化装扮外观"
schinese.buff_chemist = "肌肉猛男防化兵"
schinese.thicc_security = "健硕霸气安保主管"
schinese.desc_tf2pyro = "解锁机动特遣队化学专家的专属外观；购买后可在设置中随时启用或关闭"
schinese.desc_thiccboy = "解锁安保主管的专属外观；购买后可在设置中随时启用或关闭"

//NTF Epsilon-11
schinese.NTF = "MTF Epsilon-11 “九尾狐”"
schinese.role.NTF_Soldier = "九尾狐士兵"
schinese.role.NTF_Commander = "九尾狐指挥官"
schinese.role.NTF_Specialist = "九尾狐战斗专家"
schinese.role.NTF_Medic = "九尾狐医疗兵"
schinese.role.NTF_Sniper = "九尾狐狙击手"
schinese.role.NTF_Pilot = "九尾狐机长"

//MTF Beta-7
schinese.BETA7 = "MTF Beta-7 疯帽商"
schinese["MTF Beta-7 ''Maz Hatters''"] = "MTF Beta-7 “疯帽商”"
schinese.role.BETA7_Soldier = "Beta-7 防化兵"
schinese.role.BETA7_Cleaner = "Beta-7 清消专员"
schinese.role.BETA7_Commander = "Beta-7 指挥官"

schinese.tasks_beta7 = "重新收容 SCP，肃清 D 级，疏散科研人员"
schinese.tasks_coordinate_beta7 = "率领带领 Beta-7 特遣队"
schinese.f2_beta7 = "机动特遣队 Beta-7 专精于应对并收容具有极高生物、化学、辐射复合污染特征的极端异常，并对受其祸及的危险区域执行闪电封控洗消。该部亦负责构筑并实施针对异常病原体爆发在全球大流行时的顶层应对阻断预案。"

//MTF Nu-7
schinese.NU7 = "MTF Nu-7 落锤"
schinese["MTF Nu-7 ''Udar Molota''"] = "MTF Nu-7 “落锤”"
schinese.role.NU7_Soldier = "Nu-7  步兵"
schinese.role.NU7_Sergant = "Nu-7 作战中士"
schinese.role.NU7_Shturm = "Nu-7 突击队员"
schinese.role.NU7_Oper = "Nu-7 特战专家"
schinese.role.NU7_Granade = "Nu-7 重装掷弹兵"
schinese.role.NU7_Com = "Nu-7 指挥官"
schinese.role.NU7_Jugg = "Nu-7 无畏战士"

schinese.tasks_nu7 = "歼灭收容 SCP，肃清 D 级，安全疏散我方人员"
schinese.tasks_coordinate_nu7 = "统领指挥全小队"
schinese.f2_nu7 = "武装机动特遣队 Nu-7 拥有整整一个齐装满员营级编制，下辖三个特种步兵连、一个轻装甲连、一个主战坦克排、一个武装陆航中队、一个核生化防化排、一个工兵排及专门的战术核武分队。其主力驻扎于重武装生物收容 Site-14。该部专在各大主要站点发生最高级收容失控、外敌武装入侵或联络彻底中断等全面灾变时，充当不可阻挡的救场重锤。"

//MTF Eta-10
schinese.ETA10 = "MTF Eta-10 非礼勿视"
schinese["MTF Eta-10 ''See no evil''"] = "MTF Eta-10 “非礼勿视”"
schinese.role.ETA10_Soldier = "Eta-10 观测步兵"
schinese.role.ETA10_Spec = "Eta-10 模因特战员"
schinese.role.ETA10_Watcher = "Eta-10 警戒观察员"
schinese.role.ETA10_Commander = "Eta-10 特遣分队长"

schinese.tasks_eta10 = "收容清除 SCP 威胁，肃清 D 级反抗人员，协助撤离"
schinese.tasks_coordinate_eta10 = "领导 Eta-10 编制小队"
schinese.f2_eta10 = "机动特遣队 Eta-10 专门负责侦测、缴获并收容具有高度视觉认知危害、视线触发模因感染源的危险目标，在必须依赖间接滤镜、盲视或特殊观察手段方能安全交互的极端情境下出击。"

//Chaos Insurgency Assault Squad
schinese.CHAOS_SHTURM = "混沌分裂者精英分队"
schinese["Chaos Insurgency Assault Squad"] = "混沌分裂者精英分队"
schinese.role.Chaos_sh_soldier = "混沌分裂者精英分队突击步兵"
schinese.role.Chaos_sh_leuit = "混沌分裂者精英分队分队中尉"
schinese.role.Chaos_sh_jugg = "混沌分裂者精英分队无畏战士"

schinese.f2_chaosass = "混沌分裂者是从基金会脱离的叛离派系。最初是一支叛变分队擅自将数个核心 SCP 物品私自带走撤离并成立了自身组织。"

//MTF Pilot
schinese.role.MTF_Pilot = "特遣队运输直升机飞行员"
schinese.heli_pilot_ready = "武装直升机已完成油料加注。一切准备就绪，可以升空！"
schinese.heli_pilot_evacuation_table_no = "救援直升机机舱载荷已满员，你无法登上这架飞机进行撤离。"

//Class-D
schinese.role.ClassD_Head = "D 级领袖"

//SCP
schinese.role.SCP058 = "SCP-058"

//new scoreboard
schinese.name = "计分板"
schinese.playername = "昵称"
schinese.ping = "Ping"
schinese.level = "等级"
schinese.score = "分数"
schinese.ranks = "军衔"
schinese.badges = "勋章"

// Shaky LOGS
schinese.shlogs_charname = "角色名称"
schinese.shlogs_role = "角色"
schinese.shlogs_team = "阵营"

schinese.shlogs_setfilter = "设置筛选器"

schinese.shlogs_allrounds = "所有回合"

schinese.shlogs_round = "回合"

schinese.shlogs_checksnapshot = "查看快照"
schinese.shlogs_close = "关闭"

schinese.shlogs_dead = "死亡"

schinese.shlogs_profile = "个人资料"

schinese.shlogs_details = "详情"

schinese.shlogs_chat = "消息"
schinese.shlogs_chat_log1 = "玩家 sender 说： </ message \\>" -- DO NOT TRANSLATE sender, message

schinese.shlogs_death = "死亡"
schinese.shlogs_death_log1 = "玩家 victim 死于门" -- DO NOT TRANSLATE victim
schinese.shlogs_death_log2 = "玩家 victim 被 killer 杀害" -- DO NOT TRANSLATE victim, killer

schinese.shlogs_deathelev = "死于电梯"
schinese.shlogs_deathelev_log1 = "玩家 user 因 killer 死于电梯" -- DO NOT TRANSLATE user, victim

schinese.shlogs_icedev = "死于 SCP(409/009)"
schinese.shlogs_icedev_log1 = "玩家 user 因 killer 死于 409" -- DO NOT TRANSLATE user, killer
schinese.shlogs_icedev_log2 = "玩家 user 感染了被 killer 杀害的 409 雕像" -- DO NOT TRANSLATE user, killer
schinese.shlogs_icedev_log3 = "玩家 user 因 killer 死于 009" -- DO NOT TRANSLATE user, killer

schinese.shlogs_disconnection = "断开连接"
schinese.shlogs_disconnection_log1 = "玩家 user 已断开连接。" -- DO NOT TRANSLATE user

schinese.shlogs_drop = "丢弃武器"
schinese.shlogs_drop_log1 = "玩家 user 丢弃了武器 weapon" -- DO NOT TRANSLATE user, weapon

schinese.shlogs_pickup = "拾取武器"
schinese.shlogs_pickup_log1 = "玩家 user 拾取了武器 weapon" -- DO NOT TRANSLATE user, weapon

schinese.shlogs_spawn = "生成"
schinese.shlogs_spawn_log1 = "玩家 user 已被 reviver 复活" -- DO NOT TRANSLATE user, reviver
schinese.shlogs_spawn_log2 = "玩家 user 作为支援单位生成" -- DO NOT TRANSLATE user
schinese.shlogs_spawn_log3 = "玩家 user 通过管理员指令生成" -- DO NOT TRANSLATE user
schinese.shlogs_spawn_log4 = "玩家 user 在回合开始时生成" -- DO NOT TRANSLATE user

schinese.radio_unknown = "【未知频道】"
schinese.scp682_vulnerable_notify = " 因遭受剧毒物质严重腐蚀，暴露出弱点，现已可被高斯步枪造成穿透伤害！"
schinese.scp682_splashed = "你将致命剧毒腐蚀性液体狠狠泼洒在了 SCP-682 身上！"
schinese.scp294_scp2938_drink = "你仰头饮下了一杯致命剧毒的烈性液体……"

schinese.intercom_terminal_title = "站点广播终端"
schinese.intercom_terminal_sub = "公用调度系统"
schinese.intercom_orders_header = "战时指挥"
schinese.intercom_transmitting = "广播中"
schinese.intercom_time_left = "剩余：{s} 秒"
schinese.intercom_reboot = "信道重启中"
schinese.intercom_timer = "计时器：{s} 秒"
schinese.intercom_mil_ez = "入口区武装防卫人员"
schinese.intercom_sci_ez = "入口区科研人员"
schinese.intercom_alive_ez = "入口区残余生命读数"
schinese.intercom_detected = "侦测到：{s}"
schinese.intercom_channel_ready = "广播频段已空闲就绪"
schinese.intercom_press_e = "按下【E】键开始全区通告"
schinese.intercom_footer_hint = "【 瞄准并点击鼠标左键进行选择 】"
schinese.intercom_footer_location = "【 广播终端总机 • 入口区 】"
schinese.intercom_officer_fallback = "值班军官"

schinese.livetab_main_title = "中央信息屏"
schinese.livetab_main_sub = "设施状态"
schinese.livetab_stat_science = "科研人员"
schinese.livetab_stat_military = "武装人员"
schinese.livetab_stat_clasd = "D 级人员"
schinese.livetab_stat_unknown = "未知阵营"
schinese.livetab_broadcast_title = "紧急通报"
schinese.livetab_broadcast_sub = "全域警报系统"
schinese.livetab_broadcast_status = "正在进行全设施广播"
schinese.livetab_footer_broadcast = "【 紧急警报 • 请全体人员高度警戒 】"
schinese.livetab_preparing_title = "正在启动系统"
schinese.livetab_preparing_sub = "地下设施准备启动"
schinese.livetab_preparing_status = "设施正在启动"
schinese.livetab_nuke_title = "ALPHA 弹头"
schinese.livetab_nuke_sub = "紧急引爆程序"
schinese.livetab_nuke_engaged = "弹头引爆程序已启动"
schinese.livetab_footer_nuke = "【 引爆在即无法取消 • 立即寻找避难所 】"
schinese.livetab_footer_main = "【 设施监控系统 】"

schinese.scp914_terminal_title = "SCP-914 • 控制面板"
schinese.scp914_terminal_sub = "项目分级：SAFE • 万能转换机"
schinese.scp914_start_btn = "启动加工程序"
schinese.scp914_start_sub = "激活 SCP-914"
schinese.scp914_processing_title = "SCP-914 • 正在加工"
schinese.scp914_processing_status = "加工中"
schinese.scp914_processing_footer = "【 正在加工 • 请勿进入 】"
schinese.scp914_mode_prefix = "档位："

schinese.mtf_order_id_title = "随身佩戴身份卡"
schinese.mtf_order_id_sub = "通令全员佩戴身份卡"
schinese.mtf_order_id_announce = "命令发布：必须佩戴身份卡！"

schinese.mtf_order_weapons_title = "枪械禁令"
schinese.mtf_order_weapons_sub = "严禁未经授权人员使用军械"
schinese.mtf_order_weapons_announce = "命令发布：严禁未经授权人员使用军械！"

schinese.mtf_order_scps_title = "SCP 异常禁令"
schinese.mtf_order_scps_sub = "严禁使用 SCP 物品"
schinese.mtf_order_scps_announce = "命令发布：严禁使用 SCP 物品！"

schinese.mtf_orders_no_permission = "你的安全权限不足，无权发布命令！"
schinese.mtf_orders_unknown_order = "未知命令！"
schinese.mtf_orders_tag = "【通令】"

schinese.mtf_rank_hof = "站点总监"
schinese.mtf_rank_com = "特遣队/安保指挥官"
schinese.mtf_rank_disp = "设施调度长"
schinese.mtf_rank_mtf_left = "特遣队中尉"
schinese.mtf_rank_tg_left = "战术小队中尉"
schinese.mtf_rank_tg_com = "战术小队队长"
schinese.mtf_rank_mtf_spec = "特遣队特装专家"
schinese.mtf_rank_tg_serplus = "战术小队上士"
schinese.mtf_rank_tg_ser = "战术小队中士"
schinese.mtf_rank_mtf_shock = "特遣队突击冲锋兵"
schinese.mtf_rank_mtf_jag = "特遣队重装无畏战士"
schinese.mtf_rank_mtf_medic = "特遣队医务长"
schinese.mtf_rank_mtf_engi = "特遣队工程战工"
schinese.mtf_rank_mtf_chem = "特遣队生化防化兵"
schinese.mtf_rank_mtf_pilot = "特遣队飞行员"
schinese.mtf_rank_tg_capral = "战术小队下士"
schinese.mtf_rank_mtf_guard = "特遣队主力特勤"
schinese.mtf_rank_mtf_security = "特遣队安保干员"
schinese.mtf_rank_tg_nerd = "战术小队新进列兵"
schinese.mtf_rank_sec_chief = "安保总署长"
schinese.mtf_rank_sec_spec = "安保特派专员"
schinese.mtf_rank_sec_inv = "安保风控调查员"
schinese.mtf_rank_sec_warden = "重甲防暴牢狱长"
schinese.mtf_rank_sec_officer = "安保二级警佐"
schinese.mtf_rank_sec_escort = "押运防暴特警"
schinese.mtf_rank_sec_recruit = "安保见习干事"
schinese.intercom_backspace_close = "【退格键】关闭菜单"

schinese.scptable_header_title = "SCP 档案 • 数据库"
schinese.scptable_header_sub = "特殊收容措施"
schinese.scptable_item_id = "项目编号"
schinese.scptable_class = "收容等级"
schinese.scptable_security = "安保等级"
schinese.scptable_no_image = "暂无记录"
schinese.scptable_footer = "【 SCP 档案终端 • 安保设施 】"

schinese.body_pickup = "捡起"

schinese.perk_header_title = "战术专长选择"
schinese.perk_btn_select = "选择"
schinese.perk_footer_skip = "按退格键跳过"
schinese.perk_lone_wolf_name = "孤身一人"
schinese.perk_lone_wolf_sub = "孤勇作战"
schinese.perk_lone_wolf_desc = "当你身边没有队友各自为战时，获得额外的伤害抗性减伤减免。"
schinese.perk_together_strong_name = "团结就是力量"
schinese.perk_together_strong_sub = "战术协同"
schinese.perk_together_strong_desc = "身边每多一名同样配备此专长的友军，自身所受伤害抗性便叠加一层提升。"

ALLLANGUAGES.schinese = schinese
